package net.storm.api.widgets;

import net.runelite.api.widgets.WidgetInfo;

/**
 * Deprecated Storm widget address holder. Packed id = (group &lt;&lt; 16) | child.
 * Static fields resolve via {@link WidgetInfo} when the name exists; otherwise packed -1.
 */
@Deprecated(forRemoval = true)
public class InterfaceAddress {
    private final int packedId;

    @Deprecated(forRemoval = true)
    public InterfaceAddress(int packedId) {
        this.packedId = packedId;
    }

    @Deprecated(forRemoval = true)
    public static InterfaceAddress fromPackedId(int packedId) {
        return new InterfaceAddress(packedId);
    }

    @Deprecated(forRemoval = true)
    public static InterfaceAddress fromWidgetInfo(WidgetInfo widgetInfo) {
        if (widgetInfo == null) {
            return new InterfaceAddress(-1);
        }
        return new InterfaceAddress(widgetInfo.getPackedId());
    }

    @Deprecated(forRemoval = true)
    public int getPackedId() {
        return packedId;
    }

    public int getGroupId() {
        return packedId < 0 ? -1 : packedId >> 16;
    }

    public int getChildId() {
        return packedId < 0 ? -1 : packedId & 0xFFFF;
    }

    private static InterfaceAddress named(String widgetInfoName) {
        try {
            return fromWidgetInfo(WidgetInfo.valueOf(widgetInfoName));
        } catch (Exception e) {
            return new InterfaceAddress(-1);
        }
    }

    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_1 = named("BANK_PIN_1");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_2 = named("BANK_PIN_2");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_3 = named("BANK_PIN_3");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_4 = named("BANK_PIN_4");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_5 = named("BANK_PIN_5");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_6 = named("BANK_PIN_6");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_7 = named("BANK_PIN_7");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_8 = named("BANK_PIN_8");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_9 = named("BANK_PIN_9");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress BANK_PIN_10 = named("BANK_PIN_10");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress COMBAT_STYLE_ONE = named("COMBAT_STYLE_ONE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress COMBAT_STYLE_TWO = named("COMBAT_STYLE_TWO");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress COMBAT_STYLE_THREE = named("COMBAT_STYLE_THREE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress COMBAT_STYLE_FOUR = named("COMBAT_STYLE_FOUR");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress COMBAT_SPELL_BOX = named("COMBAT_SPELL_BOX");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress COMBAT_DEFENSIVE_SPELL_BOX = named("COMBAT_DEFENSIVE_SPELL_BOX");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress FOSSIL_MUSHROOM_HOUSE = named("FOSSIL_MUSHROOM_HOUSE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress FOSSIL_MUSHROOM_VALLEY = named("FOSSIL_MUSHROOM_VALLEY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress FOSSIL_MUSHROOM_SWAMP = named("FOSSIL_MUSHROOM_SWAMP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress FOSSIL_MUSHROOM_MEADOW = named("FOSSIL_MUSHROOM_MEADOW");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_THICK_SKIN = named("PRAYER_THICK_SKIN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_BURST_OF_STRENGTH = named("PRAYER_BURST_OF_STRENGTH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_CLARITY_OF_THOUGHT = named("PRAYER_CLARITY_OF_THOUGHT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_SHARP_EYE = named("PRAYER_SHARP_EYE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_MYSTIC_WILL = named("PRAYER_MYSTIC_WILL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_ROCK_SKIN = named("PRAYER_ROCK_SKIN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_SUPERHUMAN_STRENGTH = named("PRAYER_SUPERHUMAN_STRENGTH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_IMPROVED_REFLEXES = named("PRAYER_IMPROVED_REFLEXES");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_RAPID_RESTORE = named("PRAYER_RAPID_RESTORE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_RAPID_HEAL = named("PRAYER_RAPID_HEAL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_PROTECT_ITEM = named("PRAYER_PROTECT_ITEM");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_HAWK_EYE = named("PRAYER_HAWK_EYE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_MYSTIC_LORE = named("PRAYER_MYSTIC_LORE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_STEEL_SKIN = named("PRAYER_STEEL_SKIN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_ULTIMATE_STRENGTH = named("PRAYER_ULTIMATE_STRENGTH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_INCREDIBLE_REFLEXES = named("PRAYER_INCREDIBLE_REFLEXES");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_PROTECT_FROM_MAGIC = named("PRAYER_PROTECT_FROM_MAGIC");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_PROTECT_FROM_MISSILES = named("PRAYER_PROTECT_FROM_MISSILES");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_PROTECT_FROM_MELEE = named("PRAYER_PROTECT_FROM_MELEE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_EAGLE_EYE = named("PRAYER_EAGLE_EYE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_MYSTIC_MIGHT = named("PRAYER_MYSTIC_MIGHT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_RETRIBUTION = named("PRAYER_RETRIBUTION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_REDEMPTION = named("PRAYER_REDEMPTION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_SMITE = named("PRAYER_SMITE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_PRESERVE = named("PRAYER_PRESERVE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_CHIVALRY = named("PRAYER_CHIVALRY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_PIETY = named("PRAYER_PIETY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_RIGOUR = named("PRAYER_RIGOUR");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress PRAYER_AUGURY = named("PRAYER_AUGURY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DIALOG_NOTIFICATION_CONTINUE = named("DIALOG_NOTIFICATION_CONTINUE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DIALOG_OPTION_OPTION1 = named("DIALOG_OPTION_OPTION1");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DIALOG2_SPRITE_CONTINUE = named("DIALOG2_SPRITE_CONTINUE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_HELMET = named("EQUIPMENT_HELMET");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_CAPE = named("EQUIPMENT_CAPE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_AMULET = named("EQUIPMENT_AMULET");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_WEAPON = named("EQUIPMENT_WEAPON");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_BODY = named("EQUIPMENT_BODY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_SHIELD = named("EQUIPMENT_SHIELD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_LEGS = named("EQUIPMENT_LEGS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_GLOVES = named("EQUIPMENT_GLOVES");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_BOOTS = named("EQUIPMENT_BOOTS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_RING = named("EQUIPMENT_RING");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress EQUIPMENT_AMMO = named("EQUIPMENT_AMMO");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_ARROW_HEADS = named("SMITHING_ANVIL_ARROW_HEADS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_AXE = named("SMITHING_ANVIL_AXE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_BATTLE_AXE = named("SMITHING_ANVIL_BATTLE_AXE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_BOLTS = named("SMITHING_ANVIL_BOLTS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_CHAIN_BODY = named("SMITHING_ANVIL_CHAIN_BODY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_CLAWS = named("SMITHING_ANVIL_CLAWS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_DAGGER = named("SMITHING_ANVIL_DAGGER");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_DART_TIPS = named("SMITHING_ANVIL_DART_TIPS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_EXCLUSIVE1 = named("SMITHING_ANVIL_EXCLUSIVE1");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_EXCLUSIVE2 = named("SMITHING_ANVIL_EXCLUSIVE2");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_FULL_HELM = named("SMITHING_ANVIL_FULL_HELM");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_JAVELIN_HEADS = named("SMITHING_ANVIL_JAVELIN_HEADS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_KITE_SHIELD = named("SMITHING_ANVIL_KITE_SHIELD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_KNIVES = named("SMITHING_ANVIL_KNIVES");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_LIMBS = named("SMITHING_ANVIL_LIMBS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_LONG_SWORD = named("SMITHING_ANVIL_LONG_SWORD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_MACE = named("SMITHING_ANVIL_MACE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_MED_HELM = named("SMITHING_ANVIL_MED_HELM");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_NAILS = named("SMITHING_ANVIL_NAILS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_PLATE_BODY = named("SMITHING_ANVIL_PLATE_BODY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_PLATE_LEGS = named("SMITHING_ANVIL_PLATE_LEGS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_PLATE_SKIRT = named("SMITHING_ANVIL_PLATE_SKIRT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_SCIMITAR = named("SMITHING_ANVIL_SCIMITAR");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_SQ_SHIELD = named("SMITHING_ANVIL_SQ_SHIELD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_SWORD = named("SMITHING_ANVIL_SWORD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_TWO_H_SWORD = named("SMITHING_ANVIL_TWO_H_SWORD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SMITHING_ANVIL_WARHAMMER = named("SMITHING_ANVIL_WARHAMMER");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELLBOOK = named("SPELLBOOK");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELLBOOK_FILTERED_BOUNDS = named("SPELLBOOK_FILTERED_BOUNDS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LUMBRIDGE_HOME_TELEPORT = named("SPELL_LUMBRIDGE_HOME_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_EDGEVILLE_HOME_TELEPORT = named("SPELL_EDGEVILLE_HOME_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LUNAR_HOME_TELEPORT = named("SPELL_LUNAR_HOME_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ARCEUUS_HOME_TELEPORT = named("SPELL_ARCEUUS_HOME_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_KOUREND_HOME_TELEPORT = named("SPELL_KOUREND_HOME_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CATHERBY_HOME_TELEPORT = named("SPELL_CATHERBY_HOME_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LUNAR_FERTILE_SOIL = named("SPELL_LUNAR_FERTILE_SOIL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WIND_STRIKE = named("SPELL_WIND_STRIKE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CONFUSE = named("SPELL_CONFUSE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ENCHANT_CROSSBOW_BOLT = named("SPELL_ENCHANT_CROSSBOW_BOLT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WATER_STRIKE = named("SPELL_WATER_STRIKE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LVL_1_ENCHANT = named("SPELL_LVL_1_ENCHANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_EARTH_STRIKE = named("SPELL_EARTH_STRIKE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WEAKEN = named("SPELL_WEAKEN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FIRE_STRIKE = named("SPELL_FIRE_STRIKE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BONES_TO_BANANAS = named("SPELL_BONES_TO_BANANAS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WIND_BOLT = named("SPELL_WIND_BOLT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CURSE = named("SPELL_CURSE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BIND = named("SPELL_BIND");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LOW_LEVEL_ALCHEMY = named("SPELL_LOW_LEVEL_ALCHEMY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WATER_BOLT = named("SPELL_WATER_BOLT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_VARROCK_TELEPORT = named("SPELL_VARROCK_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LVL_2_ENCHANT = named("SPELL_LVL_2_ENCHANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_EARTH_BOLT = named("SPELL_EARTH_BOLT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LUMBRIDGE_TELEPORT = named("SPELL_LUMBRIDGE_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELEKINETIC_GRAB = named("SPELL_TELEKINETIC_GRAB");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FIRE_BOLT = named("SPELL_FIRE_BOLT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FALADOR_TELEPORT = named("SPELL_FALADOR_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CRUMBLE_UNDEAD = named("SPELL_CRUMBLE_UNDEAD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELEPORT_TO_HOUSE = named("SPELL_TELEPORT_TO_HOUSE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WIND_BLAST = named("SPELL_WIND_BLAST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SUPERHEAT_ITEM = named("SPELL_SUPERHEAT_ITEM");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CAMELOT_TELEPORT = named("SPELL_CAMELOT_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WATER_BLAST = named("SPELL_WATER_BLAST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LVL_3_ENCHANT = named("SPELL_LVL_3_ENCHANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_IBAN_BLAST = named("SPELL_IBAN_BLAST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SNARE = named("SPELL_SNARE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MAGIC_DART = named("SPELL_MAGIC_DART");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ARDOUGNE_TELEPORT = named("SPELL_ARDOUGNE_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_EARTH_BLAST = named("SPELL_EARTH_BLAST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_HIGH_LEVEL_ALCHEMY = named("SPELL_HIGH_LEVEL_ALCHEMY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CHARGE_WATER_ORB = named("SPELL_CHARGE_WATER_ORB");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LVL_4_ENCHANT = named("SPELL_LVL_4_ENCHANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WATCHTOWER_TELEPORT = named("SPELL_WATCHTOWER_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CIVITAS_ILLA_FORTIS_TELEPORT = named("SPELL_CIVITAS_ILLA_FORTIS_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FIRE_BLAST = named("SPELL_FIRE_BLAST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CHARGE_EARTH_ORB = named("SPELL_CHARGE_EARTH_ORB");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BONES_TO_PEACHES = named("SPELL_BONES_TO_PEACHES");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SARADOMIN_STRIKE = named("SPELL_SARADOMIN_STRIKE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CLAWS_OF_GUTHIX = named("SPELL_CLAWS_OF_GUTHIX");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FLAMES_OF_ZAMORAK = named("SPELL_FLAMES_OF_ZAMORAK");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TROLLHEIM_TELEPORT = named("SPELL_TROLLHEIM_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WIND_WAVE = named("SPELL_WIND_WAVE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CHARGE_FIRE_ORB = named("SPELL_CHARGE_FIRE_ORB");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELEPORT_TO_APE_ATOLL = named("SPELL_TELEPORT_TO_APE_ATOLL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WATER_WAVE = named("SPELL_WATER_WAVE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CHARGE_AIR_ORB = named("SPELL_CHARGE_AIR_ORB");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_VULNERABILITY = named("SPELL_VULNERABILITY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LVL_5_ENCHANT = named("SPELL_LVL_5_ENCHANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELEPORT_TO_KOUREND = named("SPELL_TELEPORT_TO_KOUREND");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_EARTH_WAVE = named("SPELL_EARTH_WAVE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ENFEEBLE = named("SPELL_ENFEEBLE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FIRE_WAVE = named("SPELL_FIRE_WAVE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ENTANGLE = named("SPELL_ENTANGLE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELEOTHER_LUMBRIDGE = named("SPELL_TELEOTHER_LUMBRIDGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_STUN = named("SPELL_STUN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CHARGE = named("SPELL_CHARGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WIND_SURGE = named("SPELL_WIND_SURGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELEOTHER_FALADOR = named("SPELL_TELEOTHER_FALADOR");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WATER_SURGE = named("SPELL_WATER_SURGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_BLOCK = named("SPELL_TELE_BLOCK");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LVL_6_ENCHANT = named("SPELL_LVL_6_ENCHANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELEOTHER_CAMELOT = named("SPELL_TELEOTHER_CAMELOT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_EARTH_SURGE = named("SPELL_EARTH_SURGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LVL_7_ENCHANT = named("SPELL_LVL_7_ENCHANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FIRE_SURGE = named("SPELL_FIRE_SURGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_BOAT_TO_ME = named("SPELL_TELE_BOAT_TO_ME");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_ME_TO_BOAT = named("SPELL_TELE_ME_TO_BOAT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MONSTER_INSPECT = named("SPELL_MONSTER_INSPECT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BOUNTY_TARGET_TELEPORT2 = named("SPELL_BOUNTY_TARGET_TELEPORT2");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ICE_RUSH = named("SPELL_ICE_RUSH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ICE_BLITZ = named("SPELL_ICE_BLITZ");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ICE_BURST = named("SPELL_ICE_BURST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ICE_BARRAGE = named("SPELL_ICE_BARRAGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BLOOD_RUSH = named("SPELL_BLOOD_RUSH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BLOOD_BLITZ = named("SPELL_BLOOD_BLITZ");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BLOOD_BURST = named("SPELL_BLOOD_BURST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BLOOD_BARRAGE = named("SPELL_BLOOD_BARRAGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SMOKE_RUSH = named("SPELL_SMOKE_RUSH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SMOKE_BLITZ = named("SPELL_SMOKE_BLITZ");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SMOKE_BURST = named("SPELL_SMOKE_BURST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SMOKE_BARRAGE = named("SPELL_SMOKE_BARRAGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SHADOW_RUSH = named("SPELL_SHADOW_RUSH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SHADOW_BLITZ = named("SPELL_SHADOW_BLITZ");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SHADOW_BURST = named("SPELL_SHADOW_BURST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SHADOW_BARRAGE = named("SPELL_SHADOW_BARRAGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_PADDEWWA_TELEPORT = named("SPELL_PADDEWWA_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SENNTISTEN_TELEPORT = named("SPELL_SENNTISTEN_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_KHARYRLL_TELEPORT = named("SPELL_KHARYRLL_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LASSAR_TELEPORT = named("SPELL_LASSAR_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DAREEYAK_TELEPORT = named("SPELL_DAREEYAK_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CARRALLANGER_TELEPORT = named("SPELL_CARRALLANGER_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ANNAKARL_TELEPORT = named("SPELL_ANNAKARL_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_GHORROCK_TELEPORT = named("SPELL_GHORROCK_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BOUNTY_TARGET_TELEPORT = named("SPELL_BOUNTY_TARGET_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_VENGEANCE_OTHER = named("SPELL_VENGEANCE_OTHER");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_VENGEANCE = named("SPELL_VENGEANCE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BOUNTY_TARGET_TELEPORT3 = named("SPELL_BOUNTY_TARGET_TELEPORT3");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BAKE_PIE = named("SPELL_BAKE_PIE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CURE_PLANT = named("SPELL_CURE_PLANT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MONSTER_EXAMINE = named("SPELL_MONSTER_EXAMINE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_NPC_CONTACT = named("SPELL_NPC_CONTACT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CURE_OTHER = named("SPELL_CURE_OTHER");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_HUMIDIFY = named("SPELL_HUMIDIFY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MOONCLAN_TELEPORT = named("SPELL_MOONCLAN_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_GROUP_MOONCLAN = named("SPELL_TELE_GROUP_MOONCLAN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CURE_ME = named("SPELL_CURE_ME");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_HUNTER_KIT = named("SPELL_HUNTER_KIT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WATERBIRTH_TELEPORT = named("SPELL_WATERBIRTH_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_GROUP_WATERBIRTH = named("SPELL_TELE_GROUP_WATERBIRTH");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CURE_GROUP = named("SPELL_CURE_GROUP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_STAT_SPY = named("SPELL_STAT_SPY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BARBARIAN_TELEPORT = named("SPELL_BARBARIAN_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_GROUP_BARBARIAN = named("SPELL_TELE_GROUP_BARBARIAN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SUPERGLASS_MAKE = named("SPELL_SUPERGLASS_MAKE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TAN_LEATHER = named("SPELL_TAN_LEATHER");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_KHAZARD_TELEPORT = named("SPELL_KHAZARD_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_GROUP_KHAZARD = named("SPELL_TELE_GROUP_KHAZARD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DREAM = named("SPELL_DREAM");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_STRING_JEWELLERY = named("SPELL_STRING_JEWELLERY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_STAT_RESTORE_POT_SHARE = named("SPELL_STAT_RESTORE_POT_SHARE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MAGIC_IMBUE = named("SPELL_MAGIC_IMBUE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FERTILE_SOIL = named("SPELL_FERTILE_SOIL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BOOST_POTION_SHARE = named("SPELL_BOOST_POTION_SHARE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FISHING_GUILD_TELEPORT = named("SPELL_FISHING_GUILD_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_GROUP_FISHING_GUILD = named("SPELL_TELE_GROUP_FISHING_GUILD");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_PLANK_MAKE = named("SPELL_PLANK_MAKE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CATHERBY_TELEPORT = named("SPELL_CATHERBY_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_GROUP_CATHERBY = named("SPELL_TELE_GROUP_CATHERBY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RECHARGE_DRAGONSTONE = named("SPELL_RECHARGE_DRAGONSTONE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ICE_PLATEAU_TELEPORT = named("SPELL_ICE_PLATEAU_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TELE_GROUP_ICE_PLATEAU = named("SPELL_TELE_GROUP_ICE_PLATEAU");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ENERGY_TRANSFER = named("SPELL_ENERGY_TRANSFER");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_HEAL_OTHER = named("SPELL_HEAL_OTHER");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_HEAL_GROUP = named("SPELL_HEAL_GROUP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SPELLBOOK_SWAP = named("SPELL_SPELLBOOK_SWAP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_GEOMANCY = named("SPELL_GEOMANCY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SPIN_FLAX = named("SPELL_SPIN_FLAX");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_OURANIA_TELEPORT = named("SPELL_OURANIA_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_TOOLTIP = named("SPELL_TOOLTIP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BASIC_REANIMATION = named("SPELL_BASIC_REANIMATION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ARCEUUS_LIBRARY_TELEPORT = named("SPELL_ARCEUUS_LIBRARY_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_ADEPT_REANIMATION = named("SPELL_ADEPT_REANIMATION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_EXPERT_REANIMATION = named("SPELL_EXPERT_REANIMATION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MASTER_REANIMATION = named("SPELL_MASTER_REANIMATION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DRAYNOR_MANOR_TELEPORT = named("SPELL_DRAYNOR_MANOR_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MIND_ALTAR_TELEPORT = named("SPELL_MIND_ALTAR_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESPAWN_TELEPORT = named("SPELL_RESPAWN_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SALVE_GRAVEYARD_TELEPORT = named("SPELL_SALVE_GRAVEYARD_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_FENKENSTRAINS_CASTLE_TELEPORT = named("SPELL_FENKENSTRAINS_CASTLE_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WEST_ARDOUGNE_TELEPORT = named("SPELL_WEST_ARDOUGNE_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_HARMONY_ISLAND_TELEPORT = named("SPELL_HARMONY_ISLAND_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_CEMETERY_TELEPORT = named("SPELL_CEMETERY_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_CROPS = named("SPELL_RESURRECT_CROPS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BARROWS_TELEPORT = named("SPELL_BARROWS_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_APE_ATOLL_TELEPORT = named("SPELL_APE_ATOLL_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_BATTLEFRONT_TELEPORT = named("SPELL_BATTLEFRONT_TELEPORT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_INFERIOR_DEMONBANE = named("SPELL_INFERIOR_DEMONBANE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SUPERIOR_DEMONBANE = named("SPELL_SUPERIOR_DEMONBANE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DARK_DEMONBANE = named("SPELL_DARK_DEMONBANE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_MARK_OF_DARKNESS = named("SPELL_MARK_OF_DARKNESS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_GHOSTLY_GRASP = named("SPELL_GHOSTLY_GRASP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SKELETAL_GRASP = named("SPELL_SKELETAL_GRASP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_UNDEAD_GRASP = named("SPELL_UNDEAD_GRASP");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_WARD_OF_ARCEUUS = named("SPELL_WARD_OF_ARCEUUS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_LESSER_CORRUPTION = named("SPELL_LESSER_CORRUPTION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_GREATER_CORRUPTION = named("SPELL_GREATER_CORRUPTION");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DEMONIC_OFFERING = named("SPELL_DEMONIC_OFFERING");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SINISTER_OFFERING = named("SPELL_SINISTER_OFFERING");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DEGRIME = named("SPELL_DEGRIME");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_SHADOW_VEIL = named("SPELL_SHADOW_VEIL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_VILE_VIGOUR = named("SPELL_VILE_VIGOUR");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DARK_LURE = named("SPELL_DARK_LURE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_DEATH_CHARGE = named("SPELL_DEATH_CHARGE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_LESSER_GHOST = named("SPELL_RESURRECT_LESSER_GHOST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_LESSER_SKELETON = named("SPELL_RESURRECT_LESSER_SKELETON");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_LESSER_ZOMBIE = named("SPELL_RESURRECT_LESSER_ZOMBIE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_SUPERIOR_GHOST = named("SPELL_RESURRECT_SUPERIOR_GHOST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_SUPERIOR_SKELETON = named("SPELL_RESURRECT_SUPERIOR_SKELETON");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_SUPERIOR_ZOMBIE = named("SPELL_RESURRECT_SUPERIOR_ZOMBIE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_GREATER_GHOST = named("SPELL_RESURRECT_GREATER_GHOST");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_GREATER_SKELETON = named("SPELL_RESURRECT_GREATER_SKELETON");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SPELL_RESURRECT_GREATER_ZOMBIE = named("SPELL_RESURRECT_GREATER_ZOMBIE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress MINIMAP_SPEC_CLICKBOX = named("MINIMAP_SPEC_CLICKBOX");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress MINIGAME_DIALOG_CONTINUE = named("MINIGAME_DIALOG_CONTINUE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress LEVEL_UP_CONTINUE = named("LEVEL_UP_CONTINUE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_BOX_DEPOSIT_INVENTORY = named("DEPOSIT_BOX_DEPOSIT_INVENTORY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_BOX_DEPOSIT_EQUIPMENT = named("DEPOSIT_BOX_DEPOSIT_EQUIPMENT");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_BOX_DEPOSIT_LOOT_BAG = named("DEPOSIT_BOX_DEPOSIT_LOOT_BAG");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_ONE = named("DEPOSIT_INVENTORY_QUANTITY_ONE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_FIVE = named("DEPOSIT_INVENTORY_QUANTITY_FIVE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_TEN = named("DEPOSIT_INVENTORY_QUANTITY_TEN");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_X = named("DEPOSIT_INVENTORY_QUANTITY_X");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_ALL = named("DEPOSIT_INVENTORY_QUANTITY_ALL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_VIEW_COMBAT_OPTIONS = named("SAILING_VIEW_COMBAT_OPTIONS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_NAME = named("SAILING_BOAT_NAME");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_HEALTH_BAR = named("SAILING_BOAT_HEALTH_BAR");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_TAB_BAR = named("SAILING_TAB_BAR");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_PANEL_TITLE = named("SAILING_BOAT_PANEL_TITLE");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_CREW_PANEL = named("SAILING_BOAT_CREW_PANEL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_STAT_PANEL = named("SAILING_BOAT_STAT_PANEL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_FACILITIES_PANEL = named("SAILING_BOAT_FACILITIES_PANEL");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_CONTROLS = named("SAILING_BOAT_CONTROLS");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_CREW_CAPACITY = named("SAILING_BOAT_CREW_CAPACITY");
    @Deprecated(forRemoval = true)
    public static final InterfaceAddress SAILING_BOAT_CREW_TOGGLES = named("SAILING_BOAT_CREW_TOGGLES");

    @Override
    public boolean equals(Object o) {
        return o instanceof InterfaceAddress && ((InterfaceAddress) o).packedId == packedId;
    }

    @Override
    public int hashCode() {
        return packedId;
    }
}
