package net.runelite.client.plugins.lonebot;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

/**
 * Release-notes per script (Imp / WC / Fish) — launcher News + Scripts-tab.
 * Nieuwste eerst. Bij elke script-{@code VERSION}-bump één regel toevoegen.
 */
public final class LoneBotScriptChangelog {

    public static final class Entry {
        public final String scriptId;
        public final String scriptName;
        public final String version;
        public final String date;
        public final String summary;

        public Entry(String scriptId, String scriptName, String version, String date, String summary) {
            this.scriptId = scriptId;
            this.scriptName = scriptName;
            this.version = version;
            this.date = date;
            this.summary = summary;
        }
    }

    private static final List<Entry> ENTRIES = Arrays.asList(
            new Entry("quest", "Quest Bot", "0.1.6", "2026-09-17",
                    "Full CombatBot-port (geen thin shell): Vamp/Cook/Doric/Goblin/Romeo + Imp/bank vóór GE."),
            new Entry("clue", "Beginner Clue", "0.1.20", "2026-09-17",
                    "Full CombatBot-port: emote naam-cache+Perform, map iface-scan, casket kit-cleanup."),
            new Entry("clue", "Beginner Clue", "0.1.19", "2026-09-17",
                    "Emote: match op naam (niet eerste Perform); wacht stil vóór Clap/klik."),
            new Entry("clue", "Beginner Clue", "0.1.18", "2026-09-17",
                    "Continue altijd force (ook als algemene Auto-continue dialog uit)."),
            new Entry("clue", "Beginner Clue", "0.1.17", "2026-09-17",
                    "Auto-continue: elke Continue-only dialog → Space+invoke (Dialog.autoContinue)."),
            new Entry("clue", "Beginner Clue", "0.1.16", "2026-09-17",
                    "Reldo: Continue/spatie na clue tonen — geen Talk-to loop."),
            new Entry("clue", "Beginner Clue", "0.1.15", "2026-09-17",
                    "Map-dig timing: geen Read mid-travel; dig pas aangekomen; clear walk na Dig."),
            new Entry("wc", "Woodcutting", "0.1.116", "2026-09-17",
                    "Geen Rune-axe Wield-spam onder Attack 40; hakken vanuit tas."),
            new Entry("wc", "Woodcutting", "0.1.115", "2026-09-17",
                    "Bank: logs dumpen afmaken na clue-deposit (niet hakken bij 1 vrij slot)."),
            new Entry("wc", "Woodcutting", "0.1.114", "2026-09-17",
                    "Sapling: AAA tot love-chat; known=3 → 100%; known=2 → 70%."),
            new Entry("wc", "Woodcutting", "0.1.113", "2026-09-16",
                    "Sapling Collect: spam tot 28648/49/50, geen wacht van 300ms tussen kliks."),
            new Entry("wc", "Woodcutting", "0.1.112", "2026-09-16",
                    "Sapling: 28648/28649/28650 = 1/2/3; Add-mulch alleen packed."),
            new Entry("fish", "Fishing", "0.1.41", "2026-09-16",
                    "Activity-log: bank/spot/Lure-stappen + LOOP."),
            new Entry("wc", "Woodcutting", "0.1.111", "2026-09-16",
                    "Activity-log: chop echte boomnaam + want=Yew bij mismatch."),
            new Entry("imp", "Imp Killer", "0.2.90", "2026-09-16",
                    "Activity-log: Imp-acties in gemeenschappelijk activity-bestand."),
            new Entry("wc", "Woodcutting", "0.1.110", "2026-09-16",
                    "FarWalk.keepSkillTicking: COS weer mid-pad naar Lumb yews (niet pas bij rand)."),
            new Entry("fish", "Fishing", "0.1.40", "2026-09-16",
                    "Barbarian vanaf bank: pad naar vuur ±3 (niet altijd 3102,3442)."),
            new Entry("star", "Star Miner", "0.1.107", "2026-09-16",
                    "Stars succes: +1 bij ster zichtbaar/aanwezig (1× per bezoek)."),
            new Entry("star", "Star Miner", "0.1.106", "2026-09-16",
                    "Sessie-teller succesvolle sterren (gemined + weg) in paint/debug."),
            new Entry("star", "Star Miner", "0.1.105", "2026-09-15",
                    "Park→Fish: niet hervatten op skip-werelden; Fish mag banken."),
            new Entry("star", "Star Miner", "0.1.104", "2026-09-14",
                    "Gear prep: geen 60× hopper-scan tijdens bank/overlay."),
            new Entry("star", "Star Miner", "0.1.103", "2026-09-14",
                    "Park: Fish/WC mag doorlinken — Star-watch niet tijdens travel."),
            new Entry("star", "Star Miner", "0.1.102", "2026-09-14",
                    "Al Kharid-bank: niet naar Shantay lopen als Booth-klik blocked is."),
            new Entry("star", "Star Miner", "0.1.101", "2026-09-14",
                    "Gems: Al Kharid-bank i.p.v. Arena-chest; banken klaar daarna hop (geen hop-failsafe tijdens lopen)."),
            new Entry("star", "Star Miner", "0.1.100", "2026-09-14",
                    "Geen minebare T → WC/Fish/combat; feed zegt je kunt minen → gear prep + Star."),
            new Entry("clue", "Beginner Clue", "0.1.14", "2026-09-14",
                    "GE coins: bank open houden + withdraw i.p.v. open/dicht-spam."),
            new Entry("clue", "Beginner Clue", "0.1.13", "2026-09-14",
                    "Spade-prep vóór Read; ontbreekt in bank → GE (geen bank↔scroll spam)."),
            new Entry("clue", "Beginner Clue", "0.1.12", "2026-09-14",
                    "Casket banken-optie; GE-koop kit; device banken na clue (RuneLite Hot/Cold-box)."),
            new Entry("clue", "Beginner Clue", "0.1.11", "2026-09-14",
                    "Strange device Feel: geen spam meer — wacht chat ‘The device is…’ (+ poll-failsafe)."),
            new Entry("clue", "Beginner Clue", "0.1.10", "2026-09-14",
                    "Hot/cold Feel: chat-hook + poll; wacht op device-antwoord i.p.v. spam-klik."),
            new Entry("clue", "Beginner Clue", "0.1.9", "2026-09-14",
                    "Volledige CombatBot-port: hot/cold 5 zones+warmer/colder, map-dig coords, Reldo→device, reward-close, emote Perform/BFS."),
            new Entry("star", "Star Miner", "0.1.99", "2026-09-14",
                    "Walker niet stoppen op 'Dwarven Mine' (valse COS); alleen echte COS Mine."),
            new Entry("star", "Star Miner", "0.1.98", "2026-09-14",
                    "Gems: Lumbridge i.p.v. Al Kharid vanuit swamp; lamp afmaken vóór bank-klik."),
            new Entry("star", "Star Miner", "0.1.97", "2026-09-14",
                    "Genie-lamp eerst: geen bank-klik tot Confirm (Magic alleen was niet genoeg)."),
            new Entry("star", "Star Miner", "0.1.96", "2026-09-13",
                    "Hop vast: loop + ↻ Star, zelfde wereld — niet skippen naar een andere ster."),
            new Entry("wc", "Woodcutting", "0.1.109", "2026-09-14",
                    "Sapling collect sneller: vóór roots, 3× AAA in één tick, invoke≤15."),
            new Entry("wc", "Woodcutting", "0.1.108", "2026-09-14",
                    "Sapling love-chat: strip @mes_hl_blu@ tags — slots leren (geen AAA-loop)."),
            new Entry("wc", "Woodcutting", "0.1.107", "2026-09-14",
                    "Kort-walk = Movement.SHORT_WALK_TILES (15); sapling via walkNearOrPath."),
            new Entry("wc", "Woodcutting", "0.1.106", "2026-09-14",
                    "Sapling: korte hops Movement.walk, lange pad (geen travel-pauze)."),
            new Entry("wc", "Woodcutting", "0.1.105", "2026-09-14",
                    "Draynor: in bank-kamer alleen COS, geen walk naar anker."),
            new Entry("fish", "Fishing", "0.1.39", "2026-09-14",
                    "Draynor: in bank-kamer alleen Bank-klik, geen walk naar booth."),
            new Entry("wc", "Woodcutting", "0.1.104", "2026-09-14",
                    "Sapling: love-chat hard maken; OOO zonder straal; collect sneller."),
            new Entry("wc", "Woodcutting", "0.1.103", "2026-09-14",
                    "Draynor bank: pad clear na COS — geen open/dicht-loop met walker."),
            new Entry("star", "Star Miner", "0.1.96", "2026-09-13",
                    "Hop vast: loop + ↻ Star, zelfde wereld — niet skippen naar een andere ster."),
            new Entry("star", "Star Miner", "0.1.95", "2026-09-13",
                    "Eerst hoppen, daarna lopen — geen naloop op de sterplek van een andere wereld."),
            new Entry("wc", "Woodcutting", "0.1.102", "2026-09-13",
                    "Dichtste boom (geen sticky ver weg); bank: alleen beste axe + tinderbox als FM."),
            new Entry("quest", "Quest Bot", "0.1.5", "2026-09-17",
                    "GE sticky: na leave-bank niet opnieuw openen; geen walkTo-spam tijdens climb."),
            new Entry("quest", "Quest Bot", "0.1.4", "2026-09-13",
                    "Quest-prep: Imp-JSON + BankSnapshot vóór GE (hammer/cadava/clay)."),
            new Entry("quest", "Quest Bot", "0.1.3", "2026-09-13",
                    "GE min-prijzen quest-items (wiki high + buffer) via QuestGePrices."),
            new Entry("wc", "Woodcutting", "0.1.101", "2026-09-13",
                    "Andere boom sneller: switch-cooldown + anim-poll mins omlaag."),
            new Entry("star", "Star Miner", "0.1.94", "2026-09-13",
                    "Lijst filtert members (Alleen F2P); gems naar echte bank; geen naloop op lege sterplek."),
            new Entry("wc", "Woodcutting", "0.1.100", "2026-09-13",
                    "Entling sneller spotten (r52); klik-mins omlaag, max delays gelijk."),
            new Entry("star", "Star Miner", "0.1.93", "2026-09-13",
                    "Live-lijst toont feed-sterren weer (niet leeg terwijl de bot ernaartoe loopt)."),
            new Entry("wc", "Woodcutting", "0.1.99", "2026-09-13",
                    "Rising Roots: bruin + groen spotten (event start); walk + hak groen eerst."),
            new Entry("star", "Star Miner", "0.1.92", "2026-09-13",
                    "Star-tele: Lumb/Fally vóór WorldWalker; staff telt; Cast pas stil."),
            new Entry("star", "Star Miner", "0.1.91", "2026-09-13",
                    "Feed 07.gg; lijst groen/rood; PvP-werelden filteren (Wilderness PK blijft)."),
            new Entry("wc", "Woodcutting", "0.1.98", "2026-09-13",
                    "Forestry sneller: detectie r34 + Collect/mulch delays omlaag."),
            new Entry("wc", "Woodcutting", "0.1.97", "2026-09-13",
                    "Sapling: AAA tot 3 slots (chat); daarna 100%/70% via straal 7 rond stort."),
            new Entry("quest", "Quest Bot", "0.1.2", "2026-09-13",
                    "Full CombatBot port: Cook/Doric/Goblin/Romeo/Rune/Vamp/Tutorial + bank/GE supply-chain."),
            new Entry("wc", "Woodcutting", "0.1.96", "2026-09-13",
                    "Lumb trap: Bottom-floor tijdens lopen; bank Lumb/Draynor apart vinkbaar."),
            new Entry("clue", "Beginner Clue", "0.1.8", "2026-09-13",
                    "Charlie/Reldo: COS invoke Talk-to; item via Talk niet Use; tramp-opties→scroll; Reldo continue + device stop."),
            new Entry("star", "Star Miner", "0.1.90", "2026-09-13",
                    "T9-wacht zelfde plek andere wereld: hop i.p.v. blijven staan (extra lagen telden niet)."),
            new Entry("star", "Star Miner", "0.1.89", "2026-09-12",
                    "Hop: W430 e.d. niet meer ✕ PvP Arena; alleen restricted Arena-werelden (niet Legacy Duels)."),
            new Entry("star", "Star Miner", "0.1.88", "2026-09-12",
                    "Blijf minen tot ster écht weg (hp/anim); geen hogere feed-ster tussendoor."),
            new Entry("wc", "Woodcutting", "0.1.95", "2026-09-12",
                    "Gear: beste axe bank/snapshot; GE axe-restock default uit (nog niet klaar)."),
            new Entry("fish", "Fishing", "0.1.38", "2026-09-12",
                    "GE bait-restock default uit (GE nog niet klaar)."),
            new Entry("imp", "Imp Killer", "0.2.89", "2026-09-12",
                    "GE restock default uit (GE nog niet klaar)."),
            new Entry("wc", "Woodcutting", "0.1.94", "2026-09-12",
                    "Beste axe vóór WC: inv/equip/bank-snapshot; bank withdrawt upgrade."),
            new Entry("monk", "Monk Killer", "0.1.11", "2026-09-11",
                    "Cabbage-pick: missing HP (1 hp/stuk); stock-aantal alleen bij volle HP."),
            new Entry("monk", "Monk Killer", "0.1.10", "2026-09-11",
                    "Cabbage: volle plukronde dan TOP_UP vol eten; Combat 1× clues/eat/flee."),
            new Entry("monk", "Monk Killer", "0.1.9", "2026-09-11",
                    "Na Talk-heal opnieuw Attack (geen stale interact); cabbage plukken aan/uit."),
            new Entry("monk", "Monk Killer", "0.1.8", "2026-09-11",
                    "Heal Talk-to: invoke (niet LMB=Attack); wacht dialog, anders food-fallback."),
            new Entry("monk", "Monk Killer", "0.1.7", "2026-09-11",
                    "Target: scene-BFS om muren + sticky; geen A* die walk-pad kaapt."),
            new Entry("monk", "Monk Killer", "0.1.6", "2026-09-11",
                    "Attack-target: kortste pad om muren; geen crow-flies door huis."),
            new Entry("monk", "Monk Killer", "0.1.5", "2026-09-11",
                    "Heal via Talk-to (geen monks in gevecht); dialog snel; fallback food/cabbage/bank."),
            new Entry("monk", "Monk Killer", "0.1.4", "2026-09-11",
                    "Cabbage: configureerbaar aantal + wacht op inv; monk-target op walk-steps."),
            new Entry("monk", "Monk Killer", "0.1.3", "2026-09-11",
                    "Arrive-interact: geen center-walk tijdens Attack-approach (geen heen-weer)."),
            new Entry("wc", "Woodcutting", "0.1.93", "2026-09-11",
                    "Chop fallback via InteractWalkHelper (skip walk als al bij/onderweg boom)."),
            new Entry("fish", "Fishing", "0.1.37", "2026-09-11",
                    "Spot klikbaar: pad-eind (center) wissen — geen Lure↔minimap-loop bij Barbarian."),
            new Entry("wc", "Woodcutting", "0.1.92", "2026-09-11",
                    "Boom in scene: center-pad wissen (zelfde walk↔chop-loop als Fish)."),
            new Entry("wc", "Woodcutting", "0.1.91", "2026-09-11",
                    "Chop-verify: snapshot vóór klik; bij boom geen valse walk (Draynor willow)."),
            new Entry("clue", "Beginner Clue", "0.1.7", "2026-09-11",
                    "Indoor emote: Open deur bij dest (Bob/Iffie/Flynn/GE/Aris) + arrival ≤2."),
            new Entry("clue", "Beginner Clue", "0.1.6", "2026-09-11",
                    "Enclosed NPC (Brian/Hairdresser/Doric), emote+Uri+equip, Sedridor basement."),
            new Entry("clue", "Beginner Clue", "0.1.5", "2026-09-11",
                    "Charlie FSM + Reldo doors/dialog (CombatBot port); wiki Charlie-items; bank unnoted."),
            new Entry("clue", "Beginner Clue", "0.1.4", "2026-09-11",
                    "Read-fix: CombatBot BFS widget-scan; geen spam-klik als scroll-UI al open is."),
            new Entry("clue", "Beginner Clue", "0.1.3", "2026-09-11",
                    "Per-skill interrupt: idle → resume vorige skill (geen preferredScript-overwrite)."),
            new Entry("wc", "Woodcutting", "0.1.90", "2026-09-11",
                    "Optie Clues doen: nest/scroll → Clue solver, daarna WC hervatten."),
            new Entry("fish", "Fishing", "0.1.36", "2026-09-11",
                    "Optie Clues doen: bottle/scroll → Clue solver, daarna Fish hervatten."),
            new Entry("star", "Star Miner", "0.1.87", "2026-09-12",
                    "AFK-herklik om de 2–3 min (ster er nog, minebaar); geen klik per swing."),
            new Entry("star", "Star Miner", "0.1.86", "2026-09-12",
                    "Keuze: hoogste minebare laag; anders dichtste wacht (T5→T6) binnen extra-lagen. Herklik na swing bewust."),
            new Entry("star", "Star Miner", "0.1.85", "2026-09-12",
                    "Mine-COS: walker cancelen (niet doorlopen naar stand-tegel); geen anim → zelfde ster."),
            new Entry("star", "Star Miner", "0.1.84", "2026-09-11",
                    "Optie Clues doen: geode/scroll → Clue solver, daarna Star hervatten."),
            new Entry("imp", "Imp Killer", "0.2.88", "2026-09-11",
                    "Optie Clues doen: scroll/container → Clue solver, daarna Imp hervatten."),
            new Entry("giants", "Giants", "0.1.1", "2026-09-11",
                    "Optie Clues doen: scroll/container → solver; clue-items niet als junk droppen."),
            new Entry("imps2", "Imps2", "0.1.8", "2026-09-11",
                    "Optie Clues doen: scroll/container → Clue solver, daarna Imps2 hervatten."),
            new Entry("monk", "Monk Killer", "0.1.2", "2026-09-11",
                    "Optie Clues doen: scroll/container → Clue solver, daarna Monk hervatten."),
            new Entry("clue", "Beginner Clue", "0.1.2", "2026-09-11",
                    "CombatBot-pad: geen bank-walk zonder scroll; alleen inv/grond openen; bank-scan alleen als bank open."),
            new Entry("wc", "Woodcutting", "0.1.89", "2026-09-11",
                    "Sapling piles: Collect (niet Take) via menu-invoke."),
            new Entry("wc", "Woodcutting", "0.1.88", "2026-09-11",
                    "Sapling AAA: snellere 3× Take; pile-IDs 47493–47499 (+ leaves/droppings/mushrooms)."),
            new Entry("wc", "Woodcutting", "0.1.87", "2026-09-11",
                    "Sapling: Take invoke ≤10 tegels; geen AntiBan tijdens forestry-event; Take fallback interact(0)."),
            new Entry("wc", "Woodcutting", "0.1.86", "2026-09-11",
                    "Lumb bank: courtyard-approach (walker 3207,3210 ±1); Climb alleen in zone."),
            new Entry("clue", "Beginner Clue", "0.1.1", "2026-09-10",
                    "Geen scroll: open geode/nest/bottle (inv/grond/bank); geen placeholder-loop; read non-blocking."),
            new Entry("giants", "Giants", "0.1.0", "2026-09-10",
                    "Hill Giants F2P: brass key (bank/GE/ground+hop), shed of Edge-trapdoor, hunt, loot, eigen food-bank."),
            new Entry("quest", "Quest Bot", "0.1.0", "2026-09-10",
                    "F2P quester: Cook / Goblin / Romeo / Rune / Doric / Vampire / Tutorial (core)."),
            new Entry("wc", "Woodcutting", "0.1.85", "2026-09-10",
                    "Bank-walk: sticky bank-doel (geen mid-pad switch Lumb↔Draynor)."),
            new Entry("wc", "Woodcutting", "0.1.84", "2026-09-10",
                    "Lumb-bank: trap invoke eerst + geen hop-spam op ground-approach."),
            new Entry("monk", "Monk Killer", "0.1.1", "2026-09-10",
                    "Food/bank settings + logout zonder food; eat-% en nood-flee configureerbaar."),
            new Entry("monk", "Monk Killer", "0.1.0", "2026-09-10",
                    "Monastery monks: Attack + eat + cabbage/Edge bank + flee ≤3 HP."),
            new Entry("wc", "Woodcutting", "0.1.83", "2026-09-10",
                    "Volle inv → meteen bank (geen forestry/antiban/nest die bank-walk uitstellen)."),
            new Entry("wc", "Woodcutting", "0.1.82", "2026-09-10",
                    "Boom→boom: weer COS/invoke Chop binnen 40t (niet eerst ernaartoe lopen)."),
            new Entry("wc", "Woodcutting", "0.1.81", "2026-09-10",
                    "Forestry sapling/roots/entling: Take/Chop/prune via menu-invoke (geen muis-COS)."),
            new Entry("wc", "Woodcutting", "0.1.80", "2026-09-10",
                    "Bot uit: geen center kiezen/loggen (alleen overlay-status)."),
            new Entry("fish", "Fishing", "0.1.35", "2026-09-10",
                    "Bot uit: geen center kiezen/loggen (alleen overlay-status)."),
            new Entry("star", "Star Miner", "0.1.83", "2026-09-10",
                    "Travel-mode 11 WorldWalker tot ≤30 (zelfde dropdown als 1–10)."),
            new Entry("star", "Star Miner", "0.1.82", "2026-09-10",
                    "Optie Travel via WorldWalker (default uit): tot ≤30 tegels WW, daarna Mine-COS."),
            new Entry("star", "Star Miner", "0.1.81", "2026-09-10",
                    "Travel: geen scene-ster/NPC-scan tot ≤30 tegels (hops doorlinken zoals Imp)."),
            new Entry("star", "Star Miner", "0.1.80", "2026-09-09",
                    "Mine-COS tijdens lopen (op scherm/range) — niet eerst stil op de stand-tegel."),
            new Entry("star", "Star Miner", "0.1.79", "2026-09-08",
                    "Travel blijft walkTo in de Star-loop; walker/LoopHost niet meer versnellen voor Star."),
            new Entry("wc", "Woodcutting", "0.1.79", "2026-09-09",
                    "Bank-walk fix + bark 1× client-read (geen 2.4s ticks / account-wissel-spam)."),
            new Entry("wc", "Woodcutting", "0.1.78", "2026-09-09",
                    "Bank: altijd de dichtstbijzijnde F2P-bank, spotnaam telt niet."),
            new Entry("wc", "Woodcutting", "0.1.77", "2026-09-09",
                    "Lumb trap omlaag; Edge yews blijven plakken en banken in Edgeville (niet GE)."),
            new Entry("wc", "Woodcutting", "0.1.76", "2026-09-09",
                    "Kit bark live uit container 814 + kit-qty (geen View nodig); per account."),
            new Entry("wc", "Woodcutting", "0.1.75", "2026-09-09",
                    "Kit bark per account + chat-awards (niet stale container 814); reset bij account-wissel."),
            new Entry("wc", "Woodcutting", "0.1.74", "2026-09-09",
                    "Yews: na COS-chop stop center-walk; geen loop terug naar midden."),
            new Entry("wc", "Woodcutting", "0.1.73", "2026-09-08",
                    "Lumb trap vast: plane 1/2 telt als bij bank; fail→trap-anker i.p.v. idle."),
            new Entry("wc", "Woodcutting", "0.1.72", "2026-09-08",
                    "Bank open/dicht-spam: na Bank-klik wachten i.p.v. doorlopen; deposit stabieler."),
            new Entry("wc", "Woodcutting", "0.1.71", "2026-09-08",
                    "Sapling mulch: COS Take + stand-tegel; fail→andere pile; geen feed zonder mulch."),
            new Entry("wc", "Woodcutting", "0.1.70", "2026-09-08",
                    "Sapling/mulch solver tijdelijk uit — Take-fail blokkeerde WC niet meer."),
            new Entry("wc", "Woodcutting", "0.1.69", "2026-09-08",
                    "UI: Logs (volle inv) = Bank / Firemaking / Drop (banken zichtbaar)."),
            new Entry("wc", "Woodcutting", "0.1.68", "2026-09-08",
                    "Start bij Lumb-bank: eerst trap omlaag naar yews (geen stilstand op plane 2)."),
            new Entry("wc", "Woodcutting", "0.1.67", "2026-09-08",
                    "FM-toggle is master: UI uit = geen bonfire/tinderbox (center :fm overschrijft niet meer)."),
            new Entry("wc", "Woodcutting", "0.1.66", "2026-09-06",
                    "Sapling: AAA-discovery; bij ≥2 known slots 70% vs 100% op pile-afstand (1.5×-regel)."),
            new Entry("wc", "Woodcutting", "0.1.65", "2026-09-06",
                    "Sapling: CombatBot-flow — ernaast Take×3, dan pas Add-mulch (geen feed-spam zonder mulch)."),
            new Entry("wc", "Woodcutting", "0.1.64", "2026-09-06",
                    "Kit bark live per account (container 814 / item qty) — niet gedeelde sessie-teller."),
            new Entry("wc", "Woodcutting", "0.1.63", "2026-09-06",
                    "Bank: COS open tijdens aanlopen (geen stilstand vóór Bank-klik)."),
            new Entry("fish", "Fishing", "0.1.34", "2026-09-06",
                    "Edgeville bank: COS open op afstand (zelfde BankHelper-API)."),
            new Entry("wc", "Woodcutting", "0.1.62", "2026-09-06",
                    "Chop alleen click-on-sight (op scherm); anders API-walk 6–12 naar de boom."),
            new Entry("star", "Star Miner", "0.1.78", "2026-09-08",
                    "Travel: alleen walkTo (geen Bank/hopper-scan) — zelfde doorlinken als Imp."),
            new Entry("star", "Star Miner", "0.1.77", "2026-09-07",
                    "Spell-tele via walker (A* hub-start) i.p.v. aparte Star-check na hop."),
            new Entry("star", "Star Miner", "0.1.76", "2026-09-07",
                    "Na hop: pad behouden + A* al tijdens hop — meteen lopen, geen settle/herladen."),
            new Entry("star", "Star Miner", "0.1.75", "2026-09-07",
                    "Travel-doel = loopbare tegel naast de ster (niet de geblokkeerde object-tegel)."),
            new Entry("star", "Star Miner", "0.1.74", "2026-09-07",
                    "Travel: elke tick walkTo zoals Imp; geen ster-scan tot ≤30 tegels (hops doorlinken)."),
            new Entry("star", "Star Miner", "0.1.73", "2026-09-07",
                    "AntiBan uit tijdens travel (zelfde als Imp naar de boot) — hops doorlinken i.p.v. stoppen."),
            new Entry("star", "Star Miner", "0.1.72", "2026-09-06",
                    "Zelfde walker: pad + min/max hops, doorlinken bij 2/3 van de vlag."),
            new Entry("star", "Star Miner", "0.1.71", "2026-09-06",
                    "Walk-ticks gelijk aan WorldWalker (~280–400 ms)."),
            new Entry("star", "Star Miner", "0.1.70", "2026-09-06",
                    "Walk-ticks tijdens rennen ~80–140 ms (sneller doorlinken)."),
            new Entry("star", "Star Miner", "0.1.69", "2026-09-06",
                    "Tijdens rennen snellere walk-ticks — doorlinken mist de vlag niet meer."),
            new Entry("star", "Star Miner", "0.1.68", "2026-09-06",
                    "Wacht op A*-pad: geen walk-miss/fail — daarna meteen hoppen."),
            new Entry("star", "Star Miner", "0.1.67", "2026-09-06",
                    "AntiBan camera/muis weer tijdens minen (pad clear bij ster; niet meer als 'lopend')."),
            new Entry("star", "Star Miner", "0.1.66", "2026-09-06",
                    "Na hop: oud walk-pad clearen (geen COS naar vorige ster-tegel)."),
            new Entry("star", "Star Miner", "0.1.65", "2026-09-05",
                    "Geen eigen walker: zelfde API-walk als Imp (hops 6–12). Mine ≤30 blijft interrupt."),
            new Entry("imp", "Imp Killer", "0.2.87", "2026-09-05",
                    "Bank deposit/withdraw zelfde tempo als Fish/WC (HumanBanking)."),
            new Entry("star", "Star Miner", "0.1.64", "2026-09-05",
                    "Gem-deposit zelfde bank-pacing als andere sessies."),
            new Entry("imp", "Imp Killer", "0.2.86", "2026-09-05",
                    "Naar Port Sarim: geen extra BFS per tick; walker ketent timeout-prefix tot de dock."),
            new Entry("imps2", "Imps2", "0.1.7", "2026-09-05",
                    "Zelfde walk als Imp: geen getPath vóór walkTo (geen dubbele BFS-freeze)."),
            new Entry("fish", "Fishing", "0.1.33", "2026-09-05",
                    "fallback fly lure logt 1× (niet elke vis-tick)."),
            new Entry("fish", "Fishing", "0.1.32", "2026-09-05",
                    "Na bank naar Barbarian-spot (niet west-hop); Stop: geen walk/fallback-log meer."),
            new Entry("fish", "Fishing", "0.1.31", "2026-09-05",
                    "Location-dropdown (AUTO of vaste spot uit fishingCenters) — zelfde als WC/Centers-tab."),
            new Entry("star", "Star Miner", "0.1.63", "2026-09-05",
                    "Live-sterrenlijst: members verborgen als Alleen F2P aan staat."),
            new Entry("star", "Star Miner", "0.1.62", "2026-09-05",
                    "F2P-wereldfilter blijft na hop (cache); hopper niet opnieuw openen om te filteren."),
            new Entry("star", "Star Miner", "0.1.61", "2026-09-05",
                    "F2P: members vóór doelkeuze (hopper-lijst fail-closed); tele → loop sneller (geen 4.5s wait)."),
            new Entry("star", "Star Miner", "0.1.60", "2026-09-04",
                    "Tele: Magic.cast Cast (CombatBot); land = hub-tegel, Home-CD via varp."),
            new Entry("star", "Star Miner", "0.1.59", "2026-09-04",
                    "Stop/Pauze 1× (geen spam); mode 3 geen bg-thread; jar moet :jar + ↻ Star."),
            new Entry("star", "Star Miner", "0.1.58", "2026-09-04",
                    "Travel mode 3: weer elke-tick walkTo (Imp), geen trage bg-thread / AntiBan-gaten."),
            new Entry("star", "Star Miner", "0.1.57", "2026-09-04",
                    "Coins weer voor Al Kharid-poort; poort-blokkade → skip; Stop stopt travel-bg."),
            new Entry("star", "Star Miner", "0.1.56", "2026-09-04",
                    "Lumb bank: sticky plane 2 (geen trap op/af ping-pong via Bottom-floor)."),
            new Entry("star", "Star Miner", "0.1.55", "2026-09-04",
                    "Bank-walk: sticky Draynor na Lumb-fail (geen flip die pad cleart)."),
            new Entry("imp", "Imp Killer", "0.2.85", "2026-09-04",
                    "Bank naar dock: eerst zuidweg (2866,3158) als je noord van de vulkaan staat."),
            new Entry("star", "Star Miner", "0.1.54", "2026-09-04",
                    "Bank-pad leeg: abort na 3× fail (geen stall); coins alleen oost van Al Kharid-poort."),
            new Entry("imp", "Imp Killer", "0.2.84", "2026-09-04",
                    "Loot achter boom: Take-invoke i.p.v. LMB; axe-chat → tegel 12s skippen."),
            new Entry("star", "Star Miner", "0.1.53", "2026-09-04",
                    "AntiBan.check weer in de loop (zelfde panel-toggles als Imp/WC/Fish)."),
            new Entry("star", "Star Miner", "0.1.52", "2026-09-04",
                    "Wacht mine/WC: alleen erts-rotsen (geen kale Rocks) + bruikbare axe; CombatBot-stijl."),
            new Entry("wc", "Woodcutting", "0.1.61", "2026-09-04",
                    "Na uitkap meteen volgende boom: geen rest-WC-anim-wacht + geen valse klik-verify."),
            new Entry("star", "Star Miner", "0.1.51", "2026-09-04",
                    "Bank-doel via BankHelper (zelfde Al Kharid-kant bij poort dicht)."),
            new Entry("star", "Star Miner", "0.1.50", "2026-09-04",
                    "Gear: ore mag; Al Kharid-bank + all coins; tele-kit withdraw; park-wacht → minebare → terug."),
            new Entry("star", "Star Miner", "0.1.49", "2026-09-03",
                    "Chat-fallback: speler-calls (435 vsw) als feed geen locatie heeft; zelfde F2P/quest-filter."),
            new Entry("star", "Star Miner", "0.1.48", "2026-09-03",
                    "Crafting Guild ster: alleen met Crafting 40 + apron/cape; deur openen; anders skip."),
            new Entry("star", "Star Miner", "0.1.47", "2026-09-03",
                    "F2P teles (Varrock/Lumb/Fally + Home-fallback). Gems banken optie (niet tijdens minen)."),
            new Entry("star", "Star Miner", "0.1.46", "2026-09-03",
                    "Lege locatie sneller skip (~1s). Geen T1 (min tier 2). Hop/switch sneller."),
            new Entry("star", "Star Miner", "0.1.45", "2026-09-03",
                    "Mine tijdens lopen ≤30 tegels in alle travel-modes (niet pas ernaast staan)."),
            new Entry("star", "Star Miner", "0.1.44", "2026-09-02",
                    "Te hoge ster: geen Prospect/Mine-klikken meer — alleen wachten tot level OK."),
            new Entry("star", "Star Miner", "0.1.43", "2026-09-02",
                    "Mode 5: doorlopen + Mine zodra ster ≤30 tegels (en Mining-level OK). Default travel=5."),
            new Entry("star", "Star Miner", "0.1.42", "2026-09-02",
                    "Crandor overslaan zonder Dragon Slayer / boot-gap. Geen pad → skip na 2× (geen LoopHost-stall)."),
            new Entry("star", "Star Miner", "0.1.41", "2026-09-02",
                    "10 travel-modes (Walk-only / bg-driver / Imp / interleave / short-hops / …) — combo in Star-settings."),
            new Entry("star", "Star Miner", "0.1.40", "2026-09-02",
                    "Lange aanloop = alleen ImpWalk (zoals Varrock→dock). Walker chaint eerder vóór stilstand."),
            new Entry("star", "Star Miner", "0.1.39", "2026-09-02",
                    "Walk = ImpWalk: elke tick walkTo + 280–450 ms (geen script-defer). Zelfde als Varrock→Port Sarim."),
            new Entry("star", "Star Miner", "0.1.38", "2026-09-02",
                    "Corsair Cove ster: skip als The Corsair Curse niet af is (feed + scene-check)."),
            new Entry("star", "Star Miner", "0.1.37", "2026-09-02",
                    "Geen herklik elke 20s op ster: mine-on-sight alleen tijdens aanlopen; op plek wacht tot echt vast (12s)."),
            new Entry("star", "Star Miner", "0.1.36", "2026-09-01",
                    "Hopper-check te streng: lopen gaat door. Alleen echte wereldlijst → inventory/ESC failsafe, geen dicht-loop."),
            new Entry("star", "Star Miner", "0.1.35", "2026-09-01",
                    "Laag-wissel: Mine + doorlopen (niet stil wachten). Bank-walk zelfde poll als fishing."),
            new Entry("star", "Star Miner", "0.1.34", "2026-09-01",
                    "Lopen als fishing: Mine tijdens lopen (invoke), walk-poll ~280 ms — niet eerst tot 8 tegels lopen."),
            new Entry("wc", "Woodcutting", "0.1.56", "2026-09-01",
                    "Lopen als fishing: Chop tijdens lopen (geen 4.5s-blok), walk-poll ~280 ms i.p.v. 0.8–1.4s."),
            new Entry("imp", "Imp Killer", "0.2.83", "2026-09-03",
                    "Per ongeluk vulkaan in: Climb rope omhoog, daarna weer imps. Rocks-tegel niet als walk-klik."),
            new Entry("imp", "Imp Killer", "0.2.82", "2026-09-03",
                    "Ranged: quiver checken + arrows Wielden vóór Attack (CombatBot-parity)."),
            new Entry("imp", "Imp Killer", "0.2.81", "2026-09-03",
                    "Dock-weg zuid (niet willow 3064,3254). Run via auto-run, geen orb-spam bij 0% energie."),
            new Entry("imp", "Imp Killer", "0.2.76", "2026-08-30",
                    "Walk: vaste hops 10–22, doorlinken vóór de vlag (geen mega-minimap-hop + stilstand)."),
            new Entry("star", "Star Miner", "0.1.33", "2026-09-01",
                    "Hopper meteen dicht na hop. Mine via ClickOnSight (invoke) zodra de ster in beeld is, niet eerst ernaartoe lopen."),
            new Entry("star", "Star Miner", "0.1.32", "2026-08-31",
                    "Laag-wissel T6→T5 via object-ID (niet healthbar). Overlay: hp % / hp ? / geen-npc."),
            new Entry("star", "Star Miner", "0.1.31", "2026-08-31",
                    "Object-ID was omgekeerd (41227=size-3/lvl 30, niet T7). Prospect-chat is leidend bij conflict."),
            new Entry("star", "Star Miner", "0.1.30", "2026-08-31",
                    "Eerst sterren die Mining nu aankan; pas daarna te-hoge wacht-sterren (niet blijven hangen als er een minebare is)."),
            new Entry("star", "Star Miner", "0.1.29", "2026-08-31",
                    "Tijdens minen: één Mine-klik, geen herklik elke 8s (swings zonder animatie tussendoor)."),
            new Entry("star", "Star Miner", "0.1.28", "2026-08-31",
                    "Wachten: niet elke minuut Prospect op de ster. Object-ID omhoog telt als laag omlaag (niet T8/T9 blijven wachten)."),
            new Entry("star", "Star Miner", "0.1.27", "2026-08-31",
                    "World hopper: niet ESC vóór doel; hop opent 1× en doet hopToWorld (niet 12 min openen-loop)."),
            new Entry("star", "Star Miner", "0.1.26", "2026-08-31",
                    "Te hoge ster: skip (niet blijven alchen/klikken). Alch telt niet als minen; Mine zodra de laag/level klopt. Hop: hopper open + wacht tot wereld wisselt. Opgeminede ster → volgende."),
            new Entry("star", "Star Miner", "0.1.25", "2026-08-31",
                    "Walk-miss Ice Mountain→Crafting Guild: pad via buurtegel of skip locatie. Hopper-ESC niet tijdens loop. Members-wereld niet kiezen vóór hopper-lijst."),
            new Entry("star", "Star Miner", "0.1.24", "2026-08-30",
                    "Laag-drop: object-ID even weg ≠ ster weg; geen hop, door minen tot de rock weg is."),
            new Entry("star", "Star Miner", "0.1.23", "2026-08-30",
                    "Laag-drop: object-ID + Prospect winnen van feed-T6; wacht-Prospect elke ~25s."),
            new Entry("star", "Star Miner", "0.1.22", "2026-08-30",
                    "Prospect tijdens wachten; geen Mine op te hoge/onbekende laag (T7+ mining 49); health via NPC-bar + chat."),
            new Entry("star", "Star Miner", "0.1.21", "2026-08-30",
                    "Hop sneller: na hopper-open meteen hopToWorld, 1,5s cooldown alleen na echte hop."),
            new Entry("star", "Star Miner", "0.1.20", "2026-08-30",
                    "Geen logout bij 0 minebare sterren zolang de feed vol zit. Stop stopt uitloggen. Hopper niet ESC tijdens hop."),
            new Entry("star", "Star Miner", "0.1.19", "2026-08-30",
                    "Geen hop naar skill-total/PVP als het account er niet in mag; console + lijst tonen waarom."),
            new Entry("star", "Star Miner", "0.1.18", "2026-08-30",
                    "Hop vast: Switch world alleen als het bevestigingsvenster er is, daarna echte hopToWorld."),
            new Entry("star", "Star Miner", "0.1.17", "2026-08-30",
                    "Console: geen spam meer van portal-sterren-telling elke poll."),
            new Entry("star", "Star Miner", "0.1.16", "2026-08-30",
                    "Overlay: doel (wereld, laag, locatie, tegel, afstand, hop)."),
            new Entry("star", "Star Miner", "0.1.15", "2026-08-30",
                    "Zelfde walker als Imp: hops 10–22, doorlinken vóór de gele vlag."),
            new Entry("wc", "Woodcutting", "0.1.53", "2026-08-30",
                    "Travel: geen 11s-wacht tijdens lopen — doorlinken vóór de vlag (geen pauze)."),
            new Entry("star", "Star Miner", "0.1.14", "2026-08-30",
                    "Bank-loop: geen wacht-tot-stilstand tussen walk-hops."),
            new Entry("star", "Star Miner", "0.1.13", "2026-08-30",
                    "Start bij een ster: eerst minen als het kan, anders wacht-extra of andere ster."),
            new Entry("star", "Star Miner", "0.1.12", "2026-08-30",
                    "Wacht extra lagen: 0 skip naar minebare ster, 1 = T5 wacht bij T6. Lijst filtert te-hoog niet weg."),
            new Entry("star", "Star Miner", "0.1.11", "2026-08-30",
                    "Te hoge ster: geen Mine. Optie tijdens wachten: High Alch, mine of woodcut in de buurt."),
            new Entry("star", "Star Miner", "0.1.10", "2026-08-30",
                    "Hopper sluiten vóór lopen (anders stapvoets). Switch world via menuAction, geen isHidden."),
            new Entry("star", "Star Miner", "0.1.9", "2026-08-30",
                    "Loop-start log. Hop-confirm alleen bij echte Switch-world dialoog. Geen stille hang."),
            new Entry("star", "Star Miner", "0.1.8", "2026-08-30",
                    "Optie: wachten bij te hoge ster tot Mining klopt. Hop: Switch world klikken."),
            new Entry("star", "Star Miner", "0.1.7", "2026-08-30",
                    "Geen ster bij aankomst → skip wereld. Logout: Click here eerst. Stop/Start reset. Hopper ESC."),
            new Entry("star", "Star Miner", "0.1.6", "2026-08-30",
                    "F2P-werelden: alleen bekende members skippen. Logout: knop klikken tot uitgelogd."),
            new Entry("star", "Star Miner", "0.1.5", "2026-08-30",
                    "F2P-filter = locatie + wereld. Bank dicht vóór hop. Pickaxe-sessie afmaken."),
            new Entry("star", "Star Miner", "0.1.4", "2026-08-30",
                    "Gear-prep: nearest bank, beste pickaxe die Mining toelaat, rest banken."),
            new Entry("star", "Star Miner", "0.1.3", "2026-08-30",
                    "Live ster-lijst in Star-tab (wereld + locatie), nieuwste eerst."),
            new Entry("star", "Star Miner", "0.1.2", "2026-08-30",
                    "Geen min/max-tier. Te hoog voor Mining → andere ster, anders logout. Overlay + Control-tab."),
            new Entry("star", "Star Miner", "0.1.1", "2026-08-30",
                    "OSRS Portal-feed + filters: alleen F2P-locaties, geen wilderness."),
            new Entry("star", "Star Miner", "0.1.0", "2026-08-30",
                    "Eerste versie: Discord/JSON-feed, lokale API, hop + loop + Mine."),
            new Entry("imps2", "Imps2", "0.1.2", "2026-08-29",
                    "Walk zoals steden-cirkel: elke tick walkTo, doorlinken bij de vlag (geen stop-start)."),
            new Entry("imps2", "Imps2", "0.1.1", "2026-08-29",
                    "Zichtbaar als script (Imps2-tab, sidebar). Walk-test ongewijzigd."),
            new Entry("imps2", "Imps2", "0.1.0", "2026-08-29",
                    "Walk-test: overal → Port Sarim dock, Musa → imps, terug → Draynor. Coords uit Imp script."),
            new Entry("imp", "Imp Killer", "0.2.72", "2026-08-29",
                    "Scorpion-agro: cmb > NPC×2+1 (lvl 14 → vanaf 30) geen vlucht/zone-skip, zoals CombatBot."),
            new Entry("imp", "Imp Killer", "0.2.71", "2026-08-29",
                    "Seaman/Customs niet in beeld: invoke of dichter naar de NPC-tegel (geen stilstand op de dock)."),
            new Entry("imp", "Imp Killer", "0.2.70", "2026-08-29",
                    "Travel zoals Imps2: elke tick walkTo, vast hunt-doel, geen wait-tot-stil."),
            new Entry("imp", "Imp Killer", "0.2.69", "2026-08-29",
                    "Travel terug naar gisteravond (0.2.57): walkTo + wacht, Pay-fare ≤40 tegels. Geen WorldWalker / walk-only."),
            new Entry("imp", "Imp Killer", "0.2.68", "2026-08-29",
                    "Walk-only test uit — volle hunt/bank/boot-loop weer aan."),
            new Entry("imp", "Imp Killer", "0.2.66", "2026-08-29",
                    "Tijdelijk alleen lopen (dock/hunt) om walker te testen."),
            new Entry("imp", "Imp Killer", "0.2.65", "2026-08-29",
                    "Haven-pad zoals steden-cirkel: elke tick MovementHelper.walkTo."),
            new Entry("imp", "Imp Killer", "0.2.64", "2026-08-29",
                    "Tijdens WorldWalker: Imp doet niks (geen eten/magic)."),
            new Entry("imp", "Imp Killer", "0.2.63", "2026-08-29",
                    "Dock/hunt via WorldWalker.go (zelfde als map Walk here)."),
            new Entry("imp", "Imp Killer", "0.2.62", "2026-08-29",
                    "Pay-fare pas ≤20 tegels; Musa→imps alleen pad, scorpion pas in hunt."),
            new Entry("imp", "Imp Killer", "0.2.58", "2026-08-28",
                    "Travel-wacht zoals WC (lang wachten tijdens lopen) — gaf pauzes bij de flag."),
            new Entry("imp", "Imp Killer", "0.2.57", "2026-08-28",
                    "Boot: script blijft aan; één walkTo, daarna wachten tot de klik loopt."),
            new Entry("imp", "Imp Killer", "0.2.55", "2026-08-28",
                    "Eerst pad naar dock; Pay-fare/ClickOnSight pas dichtbij (40 tegels)."),
            new Entry("wc", "Woodcutting", "0.1.51", "2026-08-29",
                    "Huidige WC — changelog vanaf hier bijhouden."),
            new Entry("fish", "Fishing", "0.1.29", "2026-08-29",
                    "Huidige Fish — changelog vanaf hier bijhouden.")
    );

    private LoneBotScriptChangelog() {
    }

    public static List<Entry> entries() {
        return Collections.unmodifiableList(ENTRIES);
    }

    public static List<Entry> forScript(String scriptId) {
        if (scriptId == null) {
            return List.of();
        }
        String id = scriptId.toLowerCase(Locale.ROOT);
        return ENTRIES.stream()
                .filter(e -> id.equals(e.scriptId))
                .collect(Collectors.toList());
    }

    /** Nieuwste samenvatting voor Scripts-tab (of {@code null}). */
    public static String latestSummary(String scriptId) {
        List<Entry> list = forScript(scriptId);
        return list.isEmpty() ? null : list.get(0).summary;
    }

    public static String asHtml() {
        StringBuilder sb = new StringBuilder();
        sb.append("<div style='margin:16px 0 8px 0;color:#f0a050;'><b>Scripts</b></div>");
        String lastName = "";
        for (Entry e : ENTRIES) {
            if (!e.scriptName.equals(lastName)) {
                lastName = e.scriptName;
                sb.append("<div style='margin:10px 0 4px 0;color:#c8d4e8;'><b>")
                        .append(escape(e.scriptName)).append("</b></div>");
            }
            sb.append("<div style='margin:0 0 8px 12px;'>")
                    .append("<b style='color:#8ec8ff;'>v").append(escape(e.version)).append("</b>")
                    .append(" <span style='color:#9aa3b5;'>").append(escape(e.date)).append("</span><br>")
                    .append(escape(e.summary))
                    .append("</div>");
        }
        return sb.toString();
    }

    private static String escape(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
