package net.runelite.client.plugins.lonebot;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Korte release-notes voor de launcher News-tab.
 * Nieuwste eerst — bij elke taak één regel toevoegen.
 */
public final class LoneBotChangelog {

    public static final class Entry {
        public final String version;
        public final String date;
        /** Max. ~1 zin. */
        public final String summary;

        public Entry(String version, String date, String summary) {
            this.version = version;
            this.date = date;
            this.summary = summary;
        }
    }

    private static final List<Entry> ENTRIES = Arrays.asList(
            new Entry("0.3.657", "2026-09-30",
                    "OAuth: password-stap hard (OTP nooit in WW); passDone-reset bij Cloudflare/need-pass."),
            new Entry("0.3.656", "2026-09-30",
                    "OAuth: OTP/mail pas ná wachtwoord; Cloudflare-wacht; geen OTP in password-veld."),
            new Entry("0.3.655", "2026-09-30",
                    "OAuth mail: nooit oude lastCode; verse code max 60s, anders skip."),
            new Entry("0.3.654", "2026-09-30",
                    "2FA OAuth: AUTO OTP→mail na 2 fails; geleerde verify-methode (otp/mail) onthouden."),
            new Entry("0.3.653", "2026-09-30",
                    "OAuth consent in zelfde venster (cookies) + auto Allow/Continue → daarna pas creds."),
            new Entry("0.3.652", "2026-09-30",
                    "OAuth OTP: 1e fout → nieuwe code; 2e fout → 20s wachten (geen spam)."),
            new Entry("0.3.651", "2026-09-30",
                    "OAuth autofill: e-mail/Continue betrouwbaar (React-fill + geen blinde stappen)."),
            new Entry("0.3.650", "2026-09-30",
                    "2FA dubbelklik → OAuth-loginvenster (autofill e-mail/WW/OTP), geen Jagex Launcher."),
            new Entry("0.3.649", "2026-09-30",
                    "Jagex login: cookie-banner (Your Privacy) automatisch wegklikken."),
            new Entry("0.3.648", "2026-09-30",
                    "Accounts: Jagex OAuth mini-login → session/characters + credentials.properties."),
            new Entry("0.3.647", "2026-09-30",
                    "2FA ghost: Jagex hard starten (exe/snelkoppeling) + venster via titel/pid."),
            new Entry("0.3.646", "2026-09-30",
                    "2FA: ghost-login via UI Automation — geen muis/toetsenbord-overname."),
            new Entry("0.3.645", "2026-09-30",
                    "2FA: Jagex dock (owned window) i.p.v. kapotte Electron-embed; typen via paneel."),
            new Entry("0.3.644", "2026-09-30",
                    "2FA: Jagex Launcher embed in eigen LoneBot-venster (OTP-typen via host)."),
            new Entry("0.3.643", "2026-09-30",
                    "2FA: OTP cijfer-voor-cijfer in 6 vakjes + Continue; Play tijdelijk uit."),
            new Entry("0.3.642", "2026-09-30",
                    "2FA: verificatie-klik gefixt (focus + knop-band OTP/mail)."),
            new Entry("0.3.641", "2026-09-30",
                    "2FA Jagex: verificatie OTP vs mail, verse mail-code, door tot Play."),
            new Entry("0.3.640", "2026-09-30",
                    "2FA: dubbelklik account typt e-mail/WW/OTP in open Jagex Launcher."),
            new Entry("0.3.639", "2026-09-30",
                    "Launcher-tab 2FA Master Dashboard: selecteer e-mail → WW/OTP/mail voor Jagex login."),
            new Entry("0.3.638", "2026-09-30",
                    "Launcher: 2FA JSON-import (email/pass/secret), TOTP OTP kopiëren + bewerken."),
            new Entry("0.3.637", "2026-09-30",
                    "RL 1.13.0: pin + WalkUiZones zonder MINIMAP_WIKI_BANNER (verwijderd)."),
            new Entry("0.3.636", "2026-09-29",
                    "Alles invoke-only in-game: muis geblokkeerd behalve login; walk = alleen WALK-invoke."),
            new Entry("0.3.635", "2026-09-29",
                    "Invoke-only NPC/object interact; AntiBan muis/toets uit (walker/GE-toets nog niet)."),
            new Entry("0.3.633", "2026-09-17",
                    "Clue full-port: CombatBot emote-registry (naam+cache), map-scan 195–225, casket kit-cleanup."),
            new Entry("0.3.632", "2026-09-17",
                    "Clue emote: juiste knop (naam+Perform), wacht stil vóór klik — geen Clap-spam."),
            new Entry("0.3.631", "2026-09-17",
                    "Quest GE: sticky reis (geen bank-heropen); GE wait als walker bezig (Lumb-climb)."),
            new Entry("0.3.630", "2026-09-17",
                    "WC: geen Wield-loop op bijl onder Attack-req; BankSession 1× fail → skip."),
            new Entry("0.3.629", "2026-09-17",
                    "Sidebar scripts: Quest Bot zichtbaar; Imps2 uit de lijst (testscript)."),
            new Entry("0.3.628", "2026-09-17",
                    "WC bank: na clue-deposit sessie afmaken zodat logs ook gestort worden."),
            new Entry("0.3.627", "2026-09-17",
                    "Auto-continue dialog: aan/uit in config+DZ; Clue/Reldo altijd force."),
            new Entry("0.3.626", "2026-09-17",
                    "Dialog.autoContinue: Space+invoke bij elke Continue-only chat (Clue-loop)."),
            new Entry("0.3.625", "2026-09-17",
                    "Clue Reldo: Continue/spatie na clue tonen (geen Talk-loop); Dialog canContinue fix."),
            new Entry("0.3.624", "2026-09-17",
                    "Clue map-dig: geen Read tijdens travel; dig pas idle/op tegel; clear walk na Dig."),
            new Entry("0.3.623", "2026-09-17",
                    "WC sapling: AAA tot chat; 3 slots=100%; 2 slots=70% filler; packed 28650."),
            new Entry("0.3.622", "2026-09-16",
                    "WC sapling Collect: spam tot id wisselt (28648→49→50), dan pas inleveren."),
            new Entry("0.3.621", "2026-09-16",
                    "WC sapling: inleveren pas bij packed mulch 28650 (1=28648, 2=28649)."),
            new Entry("0.3.620", "2026-09-16",
                    "Activity-log: stappen naar bestand + Console; LOOP; optionele Discord-webhook."),
            new Entry("0.3.619", "2026-09-16",
                    "Walker: Edgeville-ruïne (Death's Domain naast yews) niet meer als pad."),
            new Entry("0.3.618", "2026-09-16",
                    "FarWalk: park-Star nooit mid-pad; alleen actieve skill bij keepSkillTicking."),
            new Entry("0.3.617", "2026-09-16",
                    "Walker: pad niet door wilderness als start en doel erbuiten liggen (Edge yews)."),
            new Entry("0.3.616", "2026-09-16",
                    "FarWalk.keepSkillTicking API: WC COS mid-approach tijdens lange walks."),
            new Entry("0.3.615", "2026-09-16",
                    "DZ sidebar: kleinere font, dropdowns full-width + brede popup (leesbare locaties)."),
            new Entry("0.3.614", "2026-09-16",
                    "Fish: Barbarian vanaf Edgeville → vuur ±3, niet altijd 3102,3442."),
            new Entry("0.3.613", "2026-09-16",
                    "Alt: null-object labels filteren (toggle Verberg null objecten)."),
            new Entry("0.3.612", "2026-09-16",
                    "Stars succes = ster aanwezig bij aankomst (niet pas na opminen). Star v0.1.107."),
            new Entry("0.3.611", "2026-09-16",
                    "Paint: timer pas bij Start; voortgang per skill (XP+duur); Stars succes-teller. Star v0.1.106."),
            new Entry("0.3.610", "2026-09-15",
                    "Bank: geen ping-pong GE ↔ Varrock West (sticky anker + geen COS op de andere booth)."),
            new Entry("0.3.608", "2026-09-14",
                    "World-lijst 1× cachen (niet 60× per Star-tick); geen feed-scan tijdens bank. Star v0.1.104."),
            new Entry("0.3.607", "2026-09-14",
                    "Bank tijdens Star-park: geen hopper-scan tussen Deposit-All; lege inv stopt de stort-loop."),
            new Entry("0.3.606", "2026-09-14",
                    "Park→Fish/WC: Star niet tijdens lopen (doorlinken i.p.v. stap-voor-stap); Star v0.1.103."),
            new Entry("0.3.605", "2026-09-14",
                    "Bank: Al Kharid-zone + geen Shantay/woestijn-omloop bij Bank-open; Star v0.1.102."),
            new Entry("0.3.604", "2026-09-14",
                    "Star gems: echte bank (niet Arena-chest), hop pas na storten; Star v0.1.101."),
            new Entry("0.3.603", "2026-09-14",
                    "Clue GE: geen bank open/dicht-loop bij coins-withdraw; Clue v0.1.14."),
            new Entry("0.3.602", "2026-09-14",
                    "Clue gear prep: spade eerst (bank→GE); geen Read/bank-loop; Clue v0.1.13."),
            new Entry("0.3.601", "2026-09-14",
                    "Launcher: tabellen/panelen licht doorzichtig zodat de wallpaper erdoorheen komt."),
            new Entry("0.3.600", "2026-09-14",
                    "Clue: DZ casket-banken + GE-kit; device banken wist Hot/Cold-overlay; Clue v0.1.12."),
            new Entry("0.3.599", "2026-09-14",
                    "Star: geen minebare tier → WC/Fish/combat; feed minebaar → Star + gear prep."),
            new Entry("0.3.598", "2026-09-14",
                    "Launcher: tandwiel-instellingen met achtergrondkeuze (origineel + 4 scenes)."),
            new Entry("0.3.597", "2026-09-14",
                    "Clue Feel-fix afgerond (chat-hook + wacht-op-antwoord); Clue v0.1.11."),
            new Entry("0.3.596", "2026-09-14",
                    "Clue hot/cold: chat-hook naar CluePlugin (Feel kreeg geen antwoord → spam-klik); Clue v0.1.10."),
            new Entry("0.3.595", "2026-09-14",
                    "Clue v0.1.9: CombatBot hot/cold+map+reward+emote port (geen thin shell)."),
            new Entry("0.3.594", "2026-09-14",
                    "Walker terug naar backup 2026-09-14 (start-gap-experimenten eruit)."),
            new Entry("0.3.593", "2026-09-14",
                    "Lamp Confirm: kleinste 'confirm'-knop i.p.v. paneel (klik landde op skill-lijst)."),
            new Entry("0.3.592", "2026-09-14",
                    "Bank: loop-score (Lumb i.p.v. Al Kharid vanaf swamp); lamp bij bank eerst."),
            new Entry("0.3.591", "2026-09-14",
                    "Lamp: na Magic alleen Confirm (geen herklik); Star klikt niet door de lamp heen."),
            new Entry("0.3.590", "2026-09-14",
                    "WC sapling collect: prioriteit vóór roots + burst takes (sneller)."),
            new Entry("0.3.589", "2026-09-14",
                    "WC sapling: strip @mes_hl_blu@ in love-chat — slots known i.p.v. AAA-forever."),
            new Entry("0.3.588", "2026-09-14",
                    "Walk start: geen 2e A* op de loop tijdens achtergrond-pad; eerste-hop-log 1× per dest."),
            new Entry("0.3.587", "2026-09-14",
                    "Walk start-gap: ver in-scene → async+quickstart (geen sync-A* op loop); walker-backup tag."),
            new Entry("0.3.586", "2026-09-14",
                    "Kort-walk gedefinieerd: Movement.SHORT_WALK_TILES=15 + walkNearOrPath."),
            new Entry("0.3.585", "2026-09-14",
                    "Rule+WC: kort Movement.walk, lang walkTo-pad (sapling hops)."),
            new Entry("0.3.584", "2026-09-14",
                    "Draynor bank-zone (Get walls): in de kamer geen walk naar eindtegel (open/dicht-loop)."),
            new Entry("0.3.583", "2026-09-14",
                    "WC sapling: love-chat slots; OOO zonder straal; sneller collect."),
            new Entry("0.3.582", "2026-09-14",
                    "Loop-stall: trage hop/walk-tick telt niet als dood (geen valse thread-herstart)."),
            new Entry("0.3.581", "2026-09-14",
                    "GE: geen Repeat Offer / geen klik op zoekprompt; abort → Collect-items, daarna Create Buy."),
            new Entry("0.3.580", "2026-09-14",
                    "Live preview: DWM pakt weer het RuneLite-gamevenster, niet LoneBot Control."),
            new Entry("0.3.579", "2026-09-14",
                    "Bank COS: pad clear zodat walker bank-UI niet dichtklikt (Draynor)."),
            new Entry("0.3.578", "2026-09-13",
                    "Break: Annuleer-knop; Play Now/Welcome tot in-world; F2P telt niet meer als wilderness."),
            new Entry("0.3.577", "2026-09-13",
                    "Break nu-knop + timer onder Start/Pauze/Stop (DZ/Accounts); sliders synchroon; launcher ☕."),
            new Entry("0.3.576", "2026-09-13",
                    "Star-hop vast: loop herstarten, daarna scripts — zelfde wereld, geen skip."),
            new Entry("0.3.575", "2026-09-13",
                    "Star: hop eerst (niet lopen op de verkeerde wereld tot de crash-tegel)."),
            new Entry("0.3.574", "2026-09-13",
                    "WC: dichtste boom; bank stort lagere bijlen / tinderbox zonder FM."),
            new Entry("0.3.573", "2026-09-13",
                    "Breaks: timer uit/in, wacht combat/loot/bank/wildy/random, script pauze+hervat, launcher-timer."),
            new Entry("0.3.570", "2026-09-13",
                    "WC: sneller andere boom (switch-cooldown + anim-poll)."),
            new Entry("0.3.569", "2026-09-13",
                    "Star: F2P-lijst zonder members-drukte; gems-bank niet op ster-tegel; stop naloop als ster weg."),
            new Entry("0.3.568", "2026-09-13",
                    "WC Entling sneller (r52); forestry klik-mins omlaag, max gelijk."),
            new Entry("0.3.567", "2026-09-13",
                    "Star-lijst: alle calls tonen (groen/rood); niet leegfilteren terwijl de bot loopt."),
            new Entry("0.3.566", "2026-09-13",
                    "GE-koop: 10s wachten; niet gevuld → abort +10%/+20%/…/+50%, daarna stop."),
            new Entry("0.3.565", "2026-09-13",
                    "WC Rising Roots: bruine roots spotten + ernaartoe; groen bij voorkeur."),
            new Entry("0.3.564", "2026-09-13",
                    "Star: Lumb/Fally tele vóór WorldWalker (staff telt; Cast pas stil)."),
            new Entry("0.3.563", "2026-09-13",
                    "Star-feed: 07.gg erbij; groen/rood; PvP-werelden uit (Wilderness PK is geen PvP)."),
            new Entry("0.3.562", "2026-09-13",
                    "WC forestry: event eerder herkend (r34); sapling Collect sneller."),
            new Entry("0.3.561", "2026-09-13",
                    "Bank: geen herhaalde Deposit-All op dezelfde stack (stale inv); één deposit per tick."),
            new Entry("0.3.557", "2026-09-13",
                    "WC sapling: chat-slots fix; recipe 100%/70% op straal 7 rond sapling."),
            new Entry("0.3.555", "2026-09-13",
                    "WC: Lumb-trap klik tijdens lopen; bank Lumb/Draynor apart aan/uit."),
            new Entry("0.3.554", "2026-09-13",
                    "Clue Charlie/Reldo: COS invoke Talk-to, geen Use-item; tramp-opties→re-read; Reldo continue+device stop."),
            new Entry("0.3.553", "2026-09-13",
                    "Star: zelfde locatie andere wereld (T9 Varrock East) → hop; extra lagen niet meer negeren."),
            new Entry("0.3.552", "2026-09-13",
                    "DZ-sidebar Script-dropdown: Beginner Clue erbij (stond al in RuneLite-sidebar)."),
            new Entry("0.3.551", "2026-09-12",
                    "Star hop: geen valse ✕ PvP Arena op gewone werelden (W430); alleen restricted Arena."),
            new Entry("0.3.550", "2026-09-12",
                    "GE-verkoop: Create Sell p0=4 + Offer op GE-inventory (467), zoals CombatBot/Storm."),
            new Entry("0.3.549", "2026-09-12",
                    "GE: geen klik op 465,6 hint/Repeat (ging naar tegels); prijs pas typen als Enter amount open is."),
            new Entry("0.3.548", "2026-09-12",
                    "GE: geen klik op slot-labels Buy/Empty of itemnaam 465,26; bezette slot View/Abort/Modify overslaan."),
            new Entry("0.3.547", "2026-09-12",
                    "GE-widgets uit capture: 465,7 Buy p0=3; 162,44/52 zoek; 465,26 qty/prijs/+5%; 465,27 = examine (geen naam)."),
            new Entry("0.3.546", "2026-09-12",
                    "GE Storm-API: getItemName leeg i.p.v. 'null (Members)'; collect alleen bij gevulde offer, geen spam."),
            new Entry("0.3.545", "2026-09-12",
                    "GE: Buy=CC_OP p0=3 op 465,7; zoek 162,44/52; qty/prijs/+5% op 465,26. Re-log uit = geen auto-login."),
            new Entry("0.3.544", "2026-09-12",
                    "GE: echte muisklik op Buy-slot + zoekrij (zelfde ids als CombatBot 465/162); geen Exchange-spam."),
            new Entry("0.3.543", "2026-09-12",
                    "GE: Storm-API (buy 5-arg, sell, open) + CombatBot zoek/qty/prijs; Test-tab koop/verkoop."),
            new Entry("0.3.542", "2026-09-12",
                    "Walk: geen spam-klik als loop-klik niks doet; laatste redmiddel Home Teleport (30 min CD)."),
            new Entry("0.3.541", "2026-09-12",
                    "Walk: geen huisdeur Open als het pad er niet doorheen gaat; vast erachter → Open om terug op het pad."),
            new Entry("0.3.540", "2026-09-12",
                    "Star: blijf minen tot ster écht weg; geen hogere feed-ster tussendoor."),
            new Entry("0.3.539", "2026-09-12",
                    "WC: beste axe via bank/snapshot; GE restock (WC/Imp/Fish) default uit (nog niet klaar)."),
            new Entry("0.3.538", "2026-09-12",
                    "Logout-test: succes = login-scherm (niet de klik-return); wacht i.p.v. meteen ⚠."),
            new Entry("0.3.537", "2026-09-12",
                    "Re-log: minder console-spam; Logout AUTO test herhaalt tot login-scherm (tab → bevestigen)."),
            new Entry("0.3.536", "2026-09-12",
                    "Re-log zelfde account (CombatBot): timer uit/in, Play Now, welkomst-lobby; Test auto-login."),
            new Entry("0.3.535", "2026-09-12",
                    "Star: AFK Mine-tik om de 2–3 min zolang de ster minebaar is."),
            new Entry("0.3.534", "2026-09-12",
                    "Star: hoogste minebare laag, anders dichtste wacht binnen extra-lagen; herklik na swing expliciet."),
            new Entry("0.3.533", "2026-09-12",
                    "Star: na Mine-COS walker stoppen — niet alsnog naar stand-tegel B."),
            new Entry("0.3.532", "2026-09-11",
                    "Monk cabbage: pluk = missing HP (1 hp/stuk); stock-aantal alleen als HP vol."),
            new Entry("0.3.531", "2026-09-11",
                    "Combat: 1× clues/eat%/flee; Monk cabbage = volle plukronde → vol eten → fight."),
            new Entry("0.3.530", "2026-09-11",
                    "Capture: speler/menu/collision + open ifaces; varbit-watch met ID-filter en noisy-mute."),
            new Entry("0.3.529", "2026-09-11",
                    "Monk: na Talk-heal niet stuck op stale interact; cabbage plukken aan/uit."),
            new Entry("0.3.528", "2026-09-11",
                    "Monk heal: Talk-to via invoke (LMB was Attack); wacht op dialog."),
            new Entry("0.3.527", "2026-09-11",
                    "Monk: scene-BFS target (geen walker-hijack) + sticky Attack; DevTools-sync fix."),
            new Entry("0.3.526", "2026-09-11",
                    "RuneLite developer mode-toggle (officiële DevTools-sidebar); client herstarten."),
            new Entry("0.3.525", "2026-09-11",
                    "Get walls: alle Wall Objects in de scan-radius (ook binnenmuren), zelfde loop als Highlight."),
            new Entry("0.3.524", "2026-09-11",
                    "Monk: heal via Talk-to + HP%-slider in DZ Combat Config; fallback cabbage/bank."),
            new Entry("0.3.523", "2026-09-11",
                    "Get walls pakt Wall Objects zoals Highlight (niet alleen flood-collision-randen)."),
            new Entry("0.3.522", "2026-09-11",
                    "Monk: cabbage-aantal + geen Pick-spam; target op loopstappen (niet crow-flies)."),
            new Entry("0.3.521", "2026-09-11",
                    "InteractWalkHelper: geen fallback-walk als al naast/onderweg (Monk/WC ping-pong)."),
            new Entry("0.3.520", "2026-09-11",
                    "Fish/WC: pad-eind wissen zodra spot/boom klikbaar is (geen walk↔interact-loop)."),
            new Entry("0.3.519", "2026-09-11",
                    "Accounts: Jagex importeren (Play → e-mail-rijen, daarna RSN uit client; geen valse hiscore-ban)."),
            new Entry("0.3.518", "2026-09-11",
                    "Accounts: Export JSON van geselecteerde accounts (login+settings) voor een andere pc."),
            new Entry("0.3.517", "2026-09-11",
                    "Clue indoor emote: deur Open bij dest (CombatBot); Clue v0.1.7."),
            new Entry("0.3.516", "2026-09-11",
                    "Clue: Brian/Hairdresser/Doric approach + emote/Uri/equip; Sedridor fix; Clue v0.1.6."),
            new Entry("0.3.515", "2026-09-11",
                    "Clue: Charlie FSM + Reldo approach/dialog (CombatBot port); Clue v0.1.5."),
            new Entry("0.3.514", "2026-09-11",
                    "Clue Read: CombatBot widget-BFS overgenomen — geen open-scroll klikloop meer."),
            new Entry("0.3.513", "2026-09-11",
                    "DZ-sidebar: Clues doen toggles op Woodcutting/Fish/Star/Giants/Imp/Combat Config."),
            new Entry("0.3.512", "2026-09-11",
                    "Per-skill Clues doen: interrupt naar Beginner Clue + auto-resume; preferredScript blijft intact."),
            new Entry("0.3.511", "2026-09-11",
                    "Beginner Clue kiesbaar in sidebar-scripts + Skills → Clue-tab (was alleen jar/catalogus)."),
            new Entry("0.3.509", "2026-09-11",
                    "Middenklik → Developer Tools-log (widget/tegel/NPC/object); niet meer lege WIDGET (geen) in Debug."),
            new Entry("0.3.507", "2026-09-11",
                    "Lumb bank: approach courtyard 3207,3210 ±1 (niet buiten 3208,3205); promote na Climb."),
            new Entry("0.3.506", "2026-09-11",
                    "Launcher: knop 🔨 Rebuild (installDist / Rebuild-LoneBot.bat) naast Herstart — Start blijft snel zonder build."),
            new Entry("0.3.505", "2026-09-11",
                    "Versie-sync: Scripts-tab Clue (catalogus/↺ Clue/hot-reload) + Clue v0.1.1 container-flow — bron lag op 502 terwijl client 504 toonde."),
            new Entry("0.3.504", "2026-09-11",
                    "(andere agent) client-bump zonder Scripts-Clue-sync in deze bron."),
            new Entry("0.3.503", "2026-09-11",
                    "(andere agent) client-bump zonder Scripts-Clue-sync in deze bron."),
            new Entry("0.3.502", "2026-09-10",
                    "Scripts-tab: Beginner Clue in catalogus + ↺ Clue; script-clue in gradle/client deps."),
            new Entry("0.3.501", "2026-09-10",
                    "Giants- en Quest-tabs tonen echte controls (niet meer coming-soon); beide op het statuspaneel."),
            new Entry("0.3.499", "2026-09-10",
                    "Quest-tab echte controls + Giants/Quest samen in de client (niet meer coming-soon)."),
            new Entry("0.3.498", "2026-09-10",
                    "Giants op het LoneBot status-paneel (actief/status/Atk XP), zoals Imp/WC/Star."),
            new Entry("0.3.497", "2026-09-10",
                    "Giants: Hill Giants als first-class script (preferredScript GIANTS, tab, brass key / shed / loot / food-bank)."),
            new Entry("0.3.497-quest", "2026-09-10",
                    "Quest Bot: F2P Cook / Goblin / Romeo / Rune / Doric / Vampire / Tutorial (core)."),
            new Entry("0.3.496", "2026-09-10",
                    "Lumb: Climb-up per verdieping (geen Top-floor vanaf grond); A* blijft 3208,3205 tot plane wisselt."),
            new Entry("0.3.495", "2026-09-10",
                    "Walk: bij Lumb-trap alleen Climb (geen omloop); bij Al Kharid-poort Pay-toll i.p.v. hop zuid langs het hek."),
            new Entry("0.3.494", "2026-09-10",
                    "Al Kharid zonder coins: poort uit, Shortest Path noordom — geen zuid-hek-omloop."),
            new Entry("0.3.493", "2026-09-10",
                    "Walk: Lumb-trap aanlopen (courtyard niet avoid); Al Kharid zonder coins zuid omlopen; geen Climb vanaf 60t."),
            new Entry("0.3.492", "2026-09-10",
                    "Walk: geen zijdeur-Open (Varrock West); Draynor→Lumb via courtyard-trap 3205,3208 daarna Climb-up."),
            new Entry("0.3.491", "2026-09-10",
                    "Walk/WW: hops alleen minimap-klik (geen invoke/canvas). Gele vlag + doorlinken zoals eerder."),
            new Entry("0.3.490", "2026-09-10",
                    "Walk: minimap-klik zet de gele vlag weer; geen invoke-spam / 40-tegel-wacht bij stilstand."),
            new Entry("0.3.489", "2026-09-10",
                    "Walk: geen 13s scene-scan (getName) per hop; invoke + viewport-walk i.p.v. muis naast het pad."),
            new Entry("0.3.488", "2026-09-10",
                    "Walker: banken-cirkel hopt meteen (geen 14s RE-scan); incomplete pad niet droppen. Rebuild-LoneBot.bat nodig."),
            new Entry("0.3.487", "2026-09-10",
                    "Walker: doorlinken 10–20 tegels, eerste hop ≤2s, F2P-teles/Pay-toll/Lumb-bank p2, Test-tab F2P banken-cirkel."),
            new Entry("0.3.486", "2026-09-10",
                    "Star WorldWalker: scripts/RE niet tijdens WW (30s-ticks); Dismiss alleen als random praat."),
            new Entry("0.3.485", "2026-09-10",
                    "Get walls scan-radius geldt weer: flood-fill stopt op de slider (4–24 tegels)."),
            new Entry("0.3.484", "2026-09-10",
                    "Monk Combat: food-% / nood-HP / bank-qty / food-bron / logout zonder food."),
            new Entry("0.3.483", "2026-09-10",
                    "Star WorldWalker: geen 30s-ticks (RE-scan) en pad niet wissen als we al naar de ster lopen."),
            new Entry("0.3.482", "2026-09-10",
                    "Walk hops invoke-first (geen muis-blok); Lumb bank: Top-floor invoke + pad clear vs ground-approach."),
            new Entry("0.3.481", "2026-09-10",
                    "Star travel-mode 11: WorldWalker tot ≤30 (zichtbaar in dezelfde dropdown als 1–10)."),
            new Entry("0.3.480", "2026-09-10",
                    "Monk Killer kiesbaar in script-dropdown + Accounts preferredScript MONK."),
            new Entry("0.3.479", "2026-09-10",
                    "Monk Killer: monastery fight + eat + cabbage/Edge bank + flee ≤3 HP (paneel Combat)."),
            new Entry("0.3.478", "2026-09-10",
                    "Centers: Combat/Mining/Fishing namen wijzigen zoals Woodcutting (kies center → Opslaan naam)."),
            new Entry("0.3.477", "2026-09-10",
                    "Star WorldWalker-handoff ≤30 + random events tijdens map-walk; map Walk-here ongewijzigd."),
            new Entry("0.3.475", "2026-09-10",
                    "Walk: doorlinken weer 4 vóór de vlag — geen 1.5s-scan/dubbel-klik per hop (stop-start)."),
            new Entry("0.3.474", "2026-09-10",
                    "Walk: in-scene meteen shortest-path (geen 15s A*-wacht); trap-scan niet per tegel 1.5s."),
            new Entry("0.3.473", "2026-09-10",
                    "Walk: tijdens lopen weer 220ms-ticks (doorlinken 4 vóór de vlag); chop-delay blijft."),
            new Entry("0.3.472", "2026-09-10",
                    "Lumb trap: Climb/Bottom-floor vanaf ≤18 tegels (was 8)."),
            new Entry("0.3.471", "2026-09-10",
                    "WC/Lumb: bank-aanloop buiten castle-avoid (A* leeg fix); trap-waypoints geen ping-pong + Bottom-floor sneller."),
            new Entry("0.3.470", "2026-09-10",
                    "Walk: dungeon-climb alleen juiste TSV-ingang (niet dichtstbijzijnde verkeerde trapdoor)."),
            new Entry("0.3.469", "2026-09-10",
                    "Walk: langs trap doorlopen zonder Climb (alleen klimmen als doel floor/dungeon vraagt)."),
            new Entry("0.3.468", "2026-09-10",
                    "Walk: na Climb-up geen meteen Climb-down (stairs reverse-blok)."),
            new Entry("0.3.467", "2026-09-10",
                    "OBJ-overlay: 1 label per multi-tile instance (niet alleen stairs)."),
            new Entry("0.3.466", "2026-09-10",
                    "OBJ-labels 1× per oid/tegel; dungeon stairs Climb-up/down (Edge Y±6400)."),
            new Entry("0.3.465", "2026-09-10",
                    "Walk: deur Open → grace doorlopen (geen dubbelklik / vast vóór open deur)."),
            new Entry("0.3.464", "2026-09-10",
                    "Walk: huisdeuren Open + naar deur lopen (geen omheen / teleport-wacht)."),
            new Entry("0.3.463", "2026-09-10",
                    "Walk: F2P SP stairs/dungeons + trapdoor Open→Climb; ESC-map-fix blijft."),
            new Entry("0.3.462", "2026-09-10",
                    "Map Walk here: ESC map-dicht cancelt WorldWalker niet meer (pad blijft)."),
            new Entry("0.3.461", "2026-09-10",
                    "WorldWalker = git HEAD: alleen f2p_gates; geen SP-all/dungeon-heuristic (A+B reset)."),
            new Entry("0.3.444", "2026-09-09",
                    "Release in repo: WC kit bark / yew center (laatste gecommitte walker-basis)."),
            new Entry("0.3.455", "2026-09-09",
                    "Walk: dungeon/trapdoor A* via transports (Edge dung); Open vóór Climb-down."),
            new Entry("0.3.454", "2026-09-09",
                    "↻ Herstart = echt installDist (Rebuild auto); LoneBot-clients dicht, andere Java blijft."),
            new Entry("0.3.453", "2026-09-09",
                    "Walk: alleen pad-deur Open (geen andere deuren); geen hop naar binnen tot open."),
            new Entry("0.3.452", "2026-09-09",
                    "Debug-console: Auto-scroll aan/uit (uit = tekst selecteren zonder wegspringen)."),
            new Entry("0.3.451", "2026-09-09",
                    "Walk: ESC stopt pad (canvas+AWT); gesloten deuren Open tijdens pathfind."),
            new Entry("0.3.450", "2026-09-09",
                    "Walker: alle Shortest Path transports (trappen/deuren/boten); legacy via -Dlonebot.walk.legacyTransports=true."),
            new Entry("0.3.449", "2026-09-09",
                    "WC-bank: walkable Lumb-aanloop (geen A* leeg op trap); geen valse COS op 40 tegels."),
            new Entry("0.3.448", "2026-09-09",
                    "Star: Mine-COS zodra de ster op scherm is (niet eerst stil staan op de stand-tegel)."),
            new Entry("0.3.447", "2026-09-09",
                    "WC-bank: altijd dichtstbijzijnde F2P-bank (naam telt niet); Corsair + Emir’s chest op de lijst."),
            new Entry("0.3.446", "2026-09-09",
                    "Sideload: jars in ~/.lonebot/sideloaded-plugins (Watchdog); Plugin Hub blijft uit."),
            new Entry("0.3.445", "2026-09-09",
                    "Lumb bank→grond: Bottom-floor + trap-hops; WC Edge yews banken in Edgeville (niet GE)."),
            new Entry("0.3.444", "2026-09-09",
                    "WC: kit-bark live per account; yews niet terug naar center na COS-chop."),
            new Entry("0.3.443", "2026-09-08",
                    "Lumb trap: geen valse ‘bezig’-cooldown; waypoints bank→trap; climb ≤5 tegels."),
            new Entry("0.3.442", "2026-09-08",
                    "Bank: na open-klik niet doorlopen; deposit wacht 2× only-keep (geen open/dicht-spam)."),
            new Entry("0.3.441", "2026-09-08",
                    "Bot uit: geen script/bank-ticks en geen ‘te traag voor doorlinken’-spam."),
            new Entry("0.3.440", "2026-09-08",
                    "Walk-tempo terug: geen 280ms-cap op alle skills; doorlinken weer 4 tegels vóór de vlag."),
            new Entry("0.3.439", "2026-09-08",
                    "Walk: Al Kharid-poort Pay-toll(10gp), geen Open/Talk-dialog."),
            new Entry("0.3.438", "2026-09-08",
                    "WC UI: Logs (volle inv) = Bank / Firemaking / Drop — banken is nu een zichtbare optie."),
            new Entry("0.3.437", "2026-09-08",
                    "Lumb bank→grond: stap naar zuid-trap + Bottom-floor; geen valse climb-success zonder walk."),
            new Entry("0.3.436", "2026-09-08",
                    "Start-fix: RuneLite weer 1.12.35 (0.3.435 zip had 1.12.38 — client kwam niet op)."),
            new Entry("0.3.435", "2026-09-08",
                    "Walk: na Varrock-tele niet meer wachten op tele-land achter je; Dialog alleen bij Al Kharid-poort."),
            new Entry("0.3.434", "2026-09-08",
                    "Walk: loop niet meer 5s blokkeren (bank-scan/randoms) — hops tijdens lopen."),
            new Entry("0.3.433", "2026-09-07",
                    "Walk: speler-stand via GameTick-cache (geen 1.5s-wait per hop) — doorlinken vóór de vlag."),
            new Entry("0.3.432", "2026-09-07",
                    "Walk: eerder doorlinken + console (s/tegels tot klik); geen hop-47; snapshot i.p.v. 8s-stall."),
            new Entry("0.3.431", "2026-09-07",
                    "Walk: hop-6 doorlinken (4 tegels vóór vlag); F2P-spell tele in A* als runes ≥35 tegels schelen."),
            new Entry("0.3.430", "2026-09-07",
                    "Walk: pad niet wissen als dest alleen naar een loopbare tegel naast het object snapt (Star 1-klik-stop)."),
            new Entry("0.3.429", "2026-09-07",
                    "Imp: Chop down uit hover/Choose Option; Chop-klik geblokkeerd (niet tijdens WC)."),
            new Entry("0.3.428", "2026-09-07",
                    "AntiBan: geen muis-fidget tijdens lopen (Star liep hopjes uit door camera/muis)."),
            new Entry("0.3.427", "2026-09-06",
                    "Walk: pad volgen, hop min–max; doorlinken bij 2/3 van de gele vlag (geen 380ms-spam)."),
            new Entry("0.3.426", "2026-09-06",
                    "Walk = WorldWalker-cadence: elke ~380ms hop VOORBIJ de vlag (geen loop-stop-klik)."),
            new Entry("0.3.425", "2026-09-06",
                    "Walk doorlinken sneller: na 1 tegel/~300ms + altijd invoke-first (minder stilstand)."),
            new Entry("0.3.424", "2026-09-06",
                    "Walk: doorlinken na ~3 tegels + snelle invoke (geen stilstand tussen hops)."),
            new Entry("0.3.423", "2026-09-06",
                    "Walk doorlinken: volgende hop 8–10 tegels vóór de vlag (geen stilstand tussen hops)."),
            new Entry("0.3.422", "2026-09-06",
                    "Walk: tijdens A*-wacht geen fail/LoopHost-stall — pad klaar → meteen hops."),
            new Entry("0.3.421", "2026-09-06",
                    "Walk: A* (Chebyshev) + wacht op volledig pad — geen incomplete quick-prefix meer."),
            new Entry("0.3.420", "2026-09-06",
                    "Al Kharid-poort: aanlopen eerst; Open/COS pas ≤20 tegels (geen klik vanaf Varrock)."),
            new Entry("0.3.419", "2026-09-06",
                    "Walk: nieuw doel wist het oude pad (na bank niet meer COS op de banktegel i.p.v. yews)."),
            new Entry("0.3.418", "2026-09-06",
                    "Walk: volgende hop 4 tegels vóór de flag (niet na 2 tegels); hop 6 klikt vaker."),
            new Entry("0.3.417", "2026-09-06",
                    "Lumb bank-floor: boven altijd COS Bank (geen walk-naar-booth vanaf trap)."),
            new Entry("0.3.416", "2026-09-06",
                    "AntiBan: stil bij walk-doel (minen) telt niet als lopen — camera/muis weer actief."),
            new Entry("0.3.415", "2026-09-06",
                    "Lumb bank-floor: vanaf trap COS Bank of walk via waypoints — geen BFS naar booth-tegel (pad leeg/stall)."),
            new Entry("0.3.414", "2026-09-06",
                    "Walk: doorlinken na ~2 tegels (niet pas 4 vóór de flag); stall wist het pad niet meer bij korte stilstand."),
            new Entry("0.3.413", "2026-09-06",
                    "Bank open = Click-on-Sight: Bank klikken tijdens aanlopen (geen stilstand vóór open)."),
            new Entry("0.3.412", "2026-09-06",
                    "Walk: stilstand-stall reset pad (geen dode route); Al Kharid-log alleen als je de poort nodig hebt."),
            new Entry("0.3.411", "2026-09-05",
                    "Walk: één API-walker, hops 6–12 op kortste pad, doorlinken vóór flag; laatste 15 padtegels click-on-sight anders hop 5."),
            new Entry("0.3.410", "2026-09-05",
                    "Bank: deposit=withdraw zelfde pacing; walk: lange paden hoppen (BFS op achtergrond)."),
            new Entry("0.3.409", "2026-09-05",
                    "Walk: BFS-timeout-prefix doorlopen en vanaf daar verder (Lumbridge→Port Sarim niet vast)."),
            new Entry("0.3.408", "2026-09-05",
                    "Walk: Al Kharid-poort alleen als dest door de poort moet (Imp/Port Sarim niet vast)."),
            new Entry("0.3.407", "2026-09-05",
                    "Fish: fallback fly lure logt 1×, niet elke vis-tick."),
            new Entry("0.3.406", "2026-09-05",
                    "Fish: na bank naar spot (niet west-hop 3081); Stop stopt walk + fallback-log."),
            new Entry("0.3.405", "2026-09-05",
                    "Dialog: chat-optie via WIDGET_CONTINUE / toets 1 / muis in chat (niet nep-CC_OP)."),
            new Entry("0.3.404", "2026-09-05",
                    "Al Kharid-poort: Yes okay / omlopen zonder coins; WorldWalker Stop-knop + ESC."),
            new Entry("0.3.403", "2026-09-05",
                    "Walk: Shortest Path/Storm Walker.buildPath (collision+poorten), geen eigen scene-cut over water."),
            new Entry("0.3.402", "2026-09-05",
                    "Walk: geen greedy cut over water (Lumbridge↔Al Kharid); alleen complete collision-route via poort/brug."),
            new Entry("0.3.401", "2026-09-04",
                    "Magic.cast = widget.interact Cast (CombatBot/CC_OP); TeleTest eist echte land-tegel, geen 8-tegel-loop."),
            new Entry("0.3.400", "2026-09-04",
                    "Stop/Pauze: AntiBan camera+muis workers echt stil (niet meer [AB/keys] na Stop)."),
            new Entry("0.3.399", "2026-09-04",
                    "Test-tab: F2P teleport-test (Home/Varrock/Lumb/Fally × Magic.cast/WIDGET_TARGET/CC_OP)."),
            new Entry("0.3.398", "2026-09-04",
                    "Walk: doorlinken tijdens rennen (~2 tegels), geen wacht tot gele vlag + 850ms."),
            new Entry("0.3.397", "2026-09-04",
                    "Star 0.1.55: bank-walk sticky (geen Lumb↔Draynor flip / pad-clear loop)."),
            new Entry("0.3.396", "2026-09-04",
                    "Walk: rollback — weer werkende hops/minimap; alleen World Map/Store mijden."),
            new Entry("0.3.395", "2026-09-04",
                    "Accounts: eigen login-wereld per account; geen stale w399 zonder voorkeur."),
            new Entry("0.3.394", "2026-09-04",
                    "Walk: weer lange soepele hops (verste veilige minimap-tegel, geen random korte stap)."),
            new Entry("0.3.393", "2026-09-04",
                    "Walk-hops op afstand 10–22 (niet pad-index); Imp dock via zuidweg, niet jungle ~2869,3187."),
            new Entry("0.3.392", "2026-09-04",
                    "Walk: minimap-klik blijft in cirkel; blokkeert orbs/Store/inv-prayer-tabs."),
            new Entry("0.3.391", "2026-09-04",
                    "Imp loot: geen canvas-LMB op items achter bomen (Chop down / need-an-axe spam)."),
            new Entry("0.3.390", "2026-09-04",
                    "Walk: minimap-klik mijdt World Map-orb; open map → ESC/close."),
            new Entry("0.3.389", "2026-09-04",
                    "Bank/walk: Al Kharid-poort dicht → bank zelfde kant (geen crow-flies naar Lumb); geen nep-omloop."),
            new Entry("0.3.388", "2026-09-04",
                    "Star Miner 0.1.50: Al Kharid bank+coins, tele-kit, park-wacht terugkeer."),
            new Entry("0.3.387", "2026-09-04",
                    "Accounts: Ctrl+klik multi-select weer + Start/Sluit = vinkjes ∪ rijselectie."),
            new Entry("0.3.386", "2026-09-04",
                    "Accounts: Rotatie → Selecteer + Select all; Start/Sluit selectie via vinkjes."),
            new Entry("0.3.385", "2026-09-03",
                    "Client-sidebar en Control-venster: settings blijven synchroon (zelfde config)."),
            new Entry("0.3.384", "2026-09-03",
                    "Star: F2P teleports + gems-banken optie/slider (niet tijdens minen)."),
            new Entry("0.3.383", "2026-09-03",
                    "Star: min-tier filter (skip T1), snellere lege-locatie skip + hop."),
            new Entry("0.3.382", "2026-09-03",
                    "Karamja-vulkaan: hops niet op Climb-down Rocks; dungeon → Climb rope (path-transport omhoog)."),
            new Entry("0.3.381", "2026-09-03",
                    "RangedAmmoKit in SDK: quiver-check + Wield ammo (Imp + andere ranged skills)."),
            new Entry("0.3.380", "2026-09-03",
                    "Run: Toggle Run niet meer bij 0% energie (Imp/walker spam). Auto-run wacht tot drempel."),
            new Entry("0.3.379", "2026-09-03",
                    "Auto-run: energie 0–10000 correct /100; geen orb-klik bij 0% of onder drempel (geen “not enough energy”)."),
            new Entry("0.3.378", "2026-09-03",
                    "Star travel-mode config terug + Mine≤30 tijdens lopen (alle modes)."),
            new Entry("0.3.377", "2026-09-01",
                    "Hopper: alleen echte wereldlijst telt als open. Lopen niet blokkeren; failsafe = inventory-tab (ESC)."),
            new Entry("0.3.376", "2026-09-01",
                    "Star/WC lopen als fishing: klikken tijdens lopen, geen 4.5s-wacht, walk-poll ~280 ms."),
            new Entry("0.3.375", "2026-09-01",
                    "Walk: hopper dicht na hop + invoke als hopper open (minimap-kliks liepen niet). Idle-reclick ~70ms i.p.v. 7s STALL."),
            new Entry("0.3.374", "2026-09-01",
                    "Anti-ban: random toetsenbord (pijltje links/rechts, zeldzamer dan muis). Eigen vinkje, niet tijdens lopen."),
            new Entry("0.3.373", "2026-09-01",
                    "Walk: hops weer 10–22 (settings). Random muis mag; tijdens travel op minimap, sneller terug, geen extra wait."),
            new Entry("0.3.372", "2026-09-01",
                    "Travel-walk: minimap-hop tot ~48 tegels (niet 10–22). Muis-toggles (random/AB) synchroon in alle vensters."),
            new Entry("0.3.371", "2026-09-01",
                    "Run-test: duidelijke AAN/UIT-regel; widget-dump alleen als [Walk/run/dbg]."),
            new Entry("0.3.370", "2026-08-31",
                    "Test-tab: Run lees / AAN / UIT (varp 173 + widget). Auto-run 8s stil tijdens de test."),
            new Entry("0.3.369", "2026-08-31",
                    "Imps dump: All niet opnieuw klikken als All al aan staat (sprite-check + 1× per trip)."),
            new Entry("0.3.368", "2026-08-31",
                    "Deposit qty: AAN=sprites 1150–1158; debug één regel 1/5/10/X/All."),
            new Entry("0.3.367", "2026-08-31",
                    "Auto-run: alleen varp 173 (niet boot-sprite/spec); Toggle Run op 160,27 — geen tweede klik die run uitzet."),
            new Entry("0.3.366", "2026-08-31",
                    "Walk: Al Kharid-poort alleen met Prince Ali Rescue of ≥10 coins — anders omlopen, geen Open-spam."),
            new Entry("0.3.365", "2026-08-31",
                    "Star: geen Prospect-klik elke ~30s tijdens wachten; live-laag zakt bij laag-wissel (niet T7→T8 via object-ID)."),
            new Entry("0.3.364", "2026-08-31",
                    "Auto-run: aan/uit via varp 173 + boot-widget 160,30 (niet 160,27). Console toont staat."),
            new Entry("0.3.362", "2026-08-31",
                    "Walk: run-orb/widget-acties op client-thread — geen crash na hop (Star bleef stapvoets/walk-miss)."),
            new Entry("0.3.361", "2026-08-31",
                    "Hop: hopper niet blijven openen (isHidden-loop); openen → wachten → hopToWorld. Star sluit hopper niet vóór hop."),
            new Entry("0.3.360", "2026-08-31",
                    "Deposit qty-test: All/1/5/10/X alleen klikken als UIT (actie weg = al aan). Imps dump slaat All-klik over."),
            new Entry("0.3.359", "2026-08-31",
                    "Show Overlay uit = alle grond-overlays van dat script uit (Imp hunt/rally/pad); status-panel blijft."),
            new Entry("0.3.358", "2026-08-31",
                    "GitHub-update neemt alle scripts mee (Imp, WC, Fish, Imps2, Star, example) naar ~/.lonebot/scripts."),
            new Entry("0.3.357", "2026-08-31",
                    "Andere PC: Scripts-Update zonder Gradle (lib-jar → ~/.lonebot/scripts). Catalogus-v ≠ in-game jar."),
            new Entry("0.3.356", "2026-08-31",
                    "Star: geen Mine/Prospect tijdens alch als de laag te hoog is; hop wacht tot de wereld écht wisselt; opgeminede ster skippen."),
            new Entry("0.3.355", "2026-08-31",
                    "Star: na hop niet vastlopen (BFS-leeg → andere start/ster); hopper niet ESC tijdens loop; F2P-wereld pas na hopper-lijst."),
            new Entry("0.3.354", "2026-08-30",
                    "Star: bij laag-drop niet hoppen — blijf minen tot de ster echt weg is."),
            new Entry("0.3.353", "2026-08-30",
                    "Star: live laag T6→T5 via object-ID + Prospect (feed niet meer vast)."),
            new Entry("0.3.352", "2026-08-30",
                    "Walk: na antiban/camera-muis snel terug naar minimap-klik (geen trage Bezier)."),
            new Entry("0.3.351", "2026-08-30",
                    "Star: Prospect tijdens wachten; geen Mine tot live laag bekend is; NPC-healthbar (10629)."),
            new Entry("0.3.350", "2026-08-30",
                    "Walk: optie geen shortcuts (default uit). Langs een stile niet meer blijven klikken; pad loopt eromheen."),
            new Entry("0.3.349", "2026-08-30",
                    "Object-IDs niet meer blijven hangen: Alt alleen via de toets, niet via muis-modifiers."),
            new Entry("0.3.348", "2026-08-30",
                    "Star hop: hopper open → meteen hopToWorld; cooldown 1,5s alleen na echte hop."),
            new Entry("0.3.347", "2026-08-30",
                    "Walk: eindklik-15 alleen t.o.v. het eindpunt — hops ver weg doorlinken weer (niet stoppen bij elke vlag)."),
            new Entry("0.3.346", "2026-08-30",
                    "Star: geen logout als de feed nog sterren heeft; Stop breekt de logout-loop."),
            new Entry("0.3.345", "2026-08-30",
                    "Star: hop-filter skill-total/PVP e.d. + reden (geen 750-wereld als F2P-skills te laag)."),
            new Entry("0.3.344", "2026-08-30",
                    "Hop: geen nepk-klik Switch world als het dialoog niet open is (Star bleef hangen)."),
            new Entry("0.3.343", "2026-08-30",
                    "Muis: pc-muis blijft van jou; alleen tijdens de bot-klik even genegeerd. Bot-klik is move+klik in één pakket."),
            new Entry("0.3.342", "2026-08-30",
                    "Fish: alleen spots in het gekozen gebied (Draynor-bait niet bij Barbarian onderweg)."),
            new Entry("0.3.341", "2026-08-30",
                    "Walk: pauze-na-klik en hop-doorlink weer instelbaar. PC-muis over het spel steelt de client-klik niet meer."),
            new Entry("0.3.340", "2026-08-30",
                    "Walk: simpel — hops ver weg, 1× eindklik binnen N tegels (default 15). Geen reclick/post-click-sliders."),
            new Entry("0.3.339", "2026-08-30",
                    "Walk: geen valse off-scene-stop; LoopHost killt de walk-tick niet meer elke 8s."),
            new Entry("0.3.338", "2026-08-30",
                    "Walk: minimap-klik zoals de werkende walker (geen cirkel-weigering). Deur-scan blokkeert lopen niet meer."),
            new Entry("0.3.337", "2026-08-30",
                    "Walk: invoke met scene-coords; geen late menuAction na timeout; klik niet meer overslaan als de muis even bezet is."),
            new Entry("0.3.336", "2026-08-30",
                    "Walk: geen BFS-herbereken van 351 tegels per tick; klik niet meer afbreken bij client-thread-timeout."),
            new Entry("0.3.335", "2026-08-30",
                    "Walk-tests: overlay/LoopWatch zien steden-cirkel; Stop stopt ze; FAIL click logt reden + invoke-fallback."),
            new Entry("0.3.334", "2026-08-30",
                    "Star: geen [Star/feed] portal-telling meer in de Console elke poll."),
            new Entry("0.3.333", "2026-08-30",
                    "Overlay: object-labels (Hole/Crystal) niet meer op NPC-pixels; NPC wint bij hover."),
            new Entry("0.3.332", "2026-08-30",
                    "Achtergrond-scan: deuren/hekken/ladders/trappen opslaan terwijl je erlangs loopt (Developer Tools)."),
            new Entry("0.3.331", "2026-08-30",
                    "Overlay: NPC-namen via NPC-definition (nid/idx); object-labels oid= niet meer over monsters."),
            new Entry("0.3.330", "2026-08-30",
                    "Walk: F2P TSV-gates/stiles (Al Kharid-poort, Lumbridge/Falador-stiles) in de pathfinder-graaf."),
            new Entry("0.3.329", "2026-08-30",
                    "Walk: globale BFS gebruikt dezelfde transport-graaf als Walker (deuren/gates zodra die geregistreerd zijn)."),
            new Entry("0.3.328", "2026-08-30",
                    "Walk: lange BFS mag afmaken (timeout ~afstand); geen greedy Falador-prefix; Open op deur/gate/stile."),
            new Entry("0.3.327", "2026-08-30",
                    "Overlay: bestemming (wereld/locatie/tegel/afstand) i.p.v. walk/cam-debug."),
            new Entry("0.3.326", "2026-08-30",
                    "Walker: vaste hops 10–22 (geen hele-minimap). Imp/Star doorlinken vóór de vlag, geen pauze."),
            new Entry("0.3.325", "2026-08-30",
                    "Walk: geen stop-start tussen hops (WC/Star wachtten tot stilstand; doorlinken eerder)."),
            new Entry("0.3.324", "2026-08-30",
                    "Star: Start al bij een ster → eerst minen of wacht-extra, niet meteen weghoppen."),
            new Entry("0.3.323", "2026-08-30",
                    "Star-tab: uitleg hoe de miner werkt + alle opties, onder Show overlay."),
            new Entry("0.3.322", "2026-08-30",
                    "Star: wacht extra lagen (0=alleen minebaar, 1=T5→T6). Te hoge sterren blijven in de lijst."),
            new Entry("0.3.321", "2026-08-30",
                    "Star: te hoge ster niet klikken; tijdens wachten High Alch / mine / WC in de buurt."),
            new Entry("0.3.320", "2026-08-30",
                    "Developer Tools: widget inspector + object-ID filter (default 7120–7126). Alt: +/− en Alt+klik."),
            new Entry("0.3.319", "2026-08-30",
                    "Hop Switch world: scan 193 zonder isHidden + diagnose. Star: hopper dicht vóór walk (minimap)."),
            new Entry("0.3.318", "2026-08-30",
                    "Test-tab: Logout & hop (Switch world). Star: geen stille hang; LoopWatch kent STAR."),
            new Entry("0.3.317", "2026-08-30",
                    "Star: wacht bij te hoge ster (optie). Hop-bevestiging: Switch world (193,0)."),
            new Entry("0.3.316", "2026-08-30",
                    "Star: hopper dicht na hop; geen ster op locatie → volgende wereld; logout via menuAction; Test-tab logout-knoppen."),
            new Entry("0.3.315", "2026-08-30",
                    "Star: F2P-filter niet alle sterren weg; logout klikt de knop (CombatBot-sequentie)."),
            new Entry("0.3.314", "2026-08-30",
                    "Star: geen hop met bank open; F2P-filter sluit members-werelden uit; auto-run spam weg."),
            new Entry("0.3.313", "2026-08-30",
                    "Star Miner: gear-prep — nearest bank, beste pickaxe, rest storten."),
            new Entry("0.3.312", "2026-08-30",
                    "Star-tab: live lijst wereld + locatie, nieuwste ster bovenaan."),
            new Entry("0.3.311", "2026-08-30",
                    "Star Miner: overlay/tab, geen tier-filter, te hoge laag → andere ster of logout."),
            new Entry("0.3.310", "2026-08-30",
                    "Star Miner: OSRS Portal als 2e feed; filter F2P + geen wilderness."),
            new Entry("0.3.309", "2026-08-30",
                    "Star Miner: Discord-feed → lokale API, world hop, lopen naar crashed stars."),
            new Entry("0.3.308", "2026-08-30",
                    "Imps: scorpion-zones groen als cmb > NPC×2+1 (CombatBot); cmb-timeout telt niet als agro."),
            new Entry("0.3.307", "2026-08-30",
                    "Imps: loot-walk niet afbreken halverwege (CombatBot: window tot de grond leeg is)."),
            new Entry("0.3.306", "2026-08-30",
                    "Imp: na Musa-boot niet meer naar Port Sarim-seaman lopen (geen pad over water)."),
            new Entry("0.3.305", "2026-08-30",
                    "Walk / Travel: Auto-run aan/uit + drempel % (OSRS orb gaat uit bij 0% energie)."),
            new Entry("0.3.304", "2026-08-29",
                    "Imp Killer: scorpion-agro formule zoals CombatBot (cmb > NPC×2+1 → geen vlucht)."),
            new Entry("0.3.303", "2026-08-29",
                    "Walk: kleine hops meteen doorlinken (geen 0,7–1,6s pauze bij de vlag)."),
            new Entry("0.3.302", "2026-08-29",
                    "Walk: minimap-klik verder naar binnen (geen rand); opnieuw richten vlak voor de klik."),
            new Entry("0.3.301", "2026-08-29",
                    "Walk: minimap-klik alleen binnen de cirkel; volgende hop als je 10–16 tegels van de vlag bent."),
            new Entry("0.3.300", "2026-08-29",
                    "Storm path-API: Walker, IWalker, WalkOptions, IMovement, TilePath.walk(options). Scripts: Movement.walkTo / Static.getWalker()."),
            new Entry("0.3.299", "2026-08-29",
                    "Storm Movement: walkTo/getPath/clearPath = pad-walker; walk = losse klik. Imps2/steden-cirkel gebruiken die API."),
            new Entry("0.3.298", "2026-08-29",
                    "Travel-walk: lange minimap-hops, doorlinken vóór de vlag, geen DBL; loop slaapt niet 0,7s tijdens rennen."),
            new Entry("0.3.297", "2026-08-29",
                    "Walk: minimap helemaal uitzoomen zodat hops niet op de rand klikken."),
            new Entry("0.3.296", "2026-08-29",
                    "Imps2 staat bij de scripts (tab, sidebar, launcher). Walk-test: dock ↔ imps ↔ Draynor."),
            new Entry("0.3.295", "2026-08-29",
                    "Imps2 walk-test: overal → Port Sarim dock → Musa → imps → terug → Draynor."),
            new Entry("0.3.294", "2026-08-29",
                    "News/Scripts: changelog per script. Imp travel terug naar gisteravond (0.2.57)."),
            new Entry("0.3.293", "2026-08-29",
                    "Walk terug naar 0.3.273: één Storm-walkTo (TilePath); excluded lokaal; stall-debug. Imp weer volledige loop."),
            new Entry("0.3.292", "2026-08-29",
                    "Travel: volgende hop voorbij de vlag in de scene (niet wachten tot je er bent — rennen was te snel)."),
            new Entry("0.3.291", "2026-08-29",
                    "Travel: volgende hop terwijl je nog ver van de vlag bent (niet eerst naar de flag lopen)."),
            new Entry("0.3.290", "2026-08-29",
                    "Loop tijdens lopen: RandomEvent/Example niet 1,2s sleep (Imp walk-test STALL tussen hops)."),
            new Entry("0.3.289", "2026-08-29",
                    "Walk travel: geen DBL-next (zette de rode vlag uit + STALL). Volgende hop op 10–16 van de flag."),
            new Entry("0.3.288", "2026-08-29",
                    "Imp naar dock: zelfde als map-walk — Imp/eten/Example tikken niet tijdens de walker."),
            new Entry("0.3.287", "2026-08-29",
                    "Walk: 2 kliks op volgende tegel = nieuwe rode vlag (geen stall op korte flag-gap)."),
            new Entry("0.3.286", "2026-08-29",
                    "Travel: geen twin/dbl ( Imp-log: DBL-next + STALL zonder flag). Sneller opnieuw klikken als je stilstaat."),
            new Entry("0.3.285", "2026-08-29",
                    "Walk twin: 2e klik op de volgende padtegel (niet dezelfde — gele flag blijft)."),
            new Entry("0.3.284", "2026-08-29",
                    "Walk: Imp/map dezelfde doorlink (niet wachten tot stilstand bij de gele flag)."),
            new Entry("0.3.283", "2026-08-29",
                    "Imp gebruikt dezelfde walker als map-walk (geen WC-wacht). WC ongewijzigd."),
            new Entry("0.3.282", "2026-08-28",
                    "Walk: doorlinken bij 2–5 van de flag (geen stop-start per hop). Imp niet 11s wachten tijdens lopen."),
            new Entry("0.3.281", "2026-08-28",
                    "Walk Storm-stijl: één klik, wachten op gele flag, geen TWIN/pad-wissen/thread-herstart."),
            new Entry("0.3.280", "2026-08-28",
                    "Imp boot: script blijft aan; loop wacht na walk-klik i.p.v. Imp uit te zetten."),
            new Entry("0.3.279", "2026-08-28",
                    "Imp boot: zelfde WorldWalker als map-Walk here — script wacht tot dock, daarna Pay-fare."),
            new Entry("0.3.278", "2026-08-28",
                    "Walk: pad volgen zonder AntiBan/hover-spam; LoopHost doodt klik niet meer (Falador→KJ boot)."),
            new Entry("0.3.277", "2026-08-28",
                    "Walk: pad niet meer door huizen; klik-deadlock gefixt (FAIL click in Falador)."),
            new Entry("0.3.276", "2026-08-28",
                    "Walk-pad altijd zichtbaar op scene + minimap (webwalker-stijl), niet alleen bij Debug Overlay."),
            new Entry("0.3.275", "2026-08-28",
                    "Walk: fidget klikt niet meer tussendoor; deuren Open; trap/ladder Climb (zelfde walker als Imp)."),
            new Entry("0.3.274", "2026-08-28",
                    "Developer Tools-tab (Storm highlights), world-map Walk here, Auto-run vanaf 20% energie."),
            new Entry("0.3.273", "2026-08-28",
                    "Walk: één Storm-walkTo (collision TilePath); excluded alleen lokaal; stall-debug in Console."),
            new Entry("0.3.272", "2026-08-28",
                    "Walk travel: Karamja dock↔hunt via scene-hops, zonder excluded tiles (geen valse Home tele)."),
            new Entry("0.3.271", "2026-08-28",
                    "Launcher Scripts-tab: filter Werkend/Beta/Test, versies, update per script (niet via game-client)."),
            new Entry("0.3.270", "2026-08-27",
                    "Walk: ver doel (jungle/dock) niet meer stil — BFS-timeout loopt door + hop 16–28 tegels."),
            new Entry("0.3.269", "2026-08-27",
                    "Imps: eenmaal bank-trip = alle loot dumpen (CombatBot); drempel stopt de dump niet."),
            new Entry("0.3.268", "2026-08-27",
                    "Imps dump: All-knop weer klikken; trip stopt niet na 1 bead; drempel = inv-slots."),
            new Entry("0.3.267", "2026-08-27",
                    "Imps: geen imp → actief zoeken rond 2841,3164 en 2846,3188 tot er één is."),
            new Entry("0.3.266", "2026-08-27",
                    "Imps deposit: beads dumpen op item-id (geen inventory-tab die de box sluit)."),
            new Entry("0.3.265", "2026-08-27",
                    "Excluded tiles gedeeld voor alle accounts (~/.lonebot/excluded-tiles.txt)."),
            new Entry("0.3.264", "2026-08-27",
                    "Updates: portable runtime/ herkend (niet meer 'installatiemap niet gevonden')."),
            new Entry("0.3.263", "2026-08-27",
                    "Imps loot: Take via invoke, geen LMB op bomen (Chop down-spam)."),
            new Entry("0.3.262", "2026-08-27",
                    "Updates: repo lonestruggle/lonebot vooraf ingevuld; token alleen nodig als de repo privé is."),
            new Entry("0.3.261", "2026-08-27",
                    "Fish: leave-walk crasht niet meer op oude Bank-SDK (↻ Scripts); minimap als bank open is."),
            new Entry("0.3.260", "2026-08-27",
                    "Fish: bank open = weglopen, geen SDK-methode die de loop crashte (↻ Scripts)."),
            new Entry("0.3.259", "2026-08-27",
                    "Fish: na banken weglopen (minimap), niet op het kruis klikken; walk op client-thread."),
            new Entry("0.3.258", "2026-08-27",
                    "Fish: doorlopen tot vis-center tot een spot ≤12 tegels is — niet halverwege stoppen."),
            new Entry("0.3.257", "2026-08-27",
                    "Bank.leaveOpenForWalk: na banken weglopen zonder Close/Esc (minimap/invoke)."),
            new Entry("0.3.256", "2026-08-27",
                    "Genie-lamp: CombatBot widget-scan (skill + Confirm), niet alleen Rub-spam."),
            new Entry("0.3.255", "2026-08-27",
                    "Walk: pad om huizen (~40 tegels) niet meer geweigerd; Fish vanaf Edgeville naar noord-rivier."),
            new Entry("0.3.254", "2026-08-27",
                    "Fish: alle spots scannen, dichtstbijzijnde bij de speler klikken (niet de overkant / 3109)."),
            new Entry("0.3.253", "2026-08-27",
                    "Sidebar DZ-look: grotere fonts; invoervelden donkergrijs (geen witte spinners/blauwe dropdowns)."),
            new Entry("0.3.252", "2026-08-27",
                    "Loot-lijsten wrappen en groeien in de hoogte (DZ-stijl), geen horizontale scroll."),
            new Entry("0.3.251", "2026-08-27",
                    "Sidebar-controls blijven in beeld; Control-venster Skills weer via tabs (geen dropdown)."),
            new Entry("0.3.250", "2026-08-27",
                    "Client: Start/Pauze/Stop terug + alle settings in DZ-stijl. Control-venster tabs ongewijzigd."),
            new Entry("0.3.249", "2026-08-27",
                    "Client-sidebar 1:1 DZ/RuneLite-config: toggle, oranje secties, label+control. Venster ongewijzigd."),
            new Entry("0.3.248", "2026-08-27",
                    "Imp: rode klik-X op de imp/loot (echte LMB), niet linksboven; loot sluit menu niet meer met hoek-klik."),
            new Entry("0.3.247", "2026-08-27",
                    "Client-sidebar: DZ-stijl accordion (geen tabs). Los Control-venster ongewijzigd."),
            new Entry("0.3.246", "2026-08-27",
                    "Sidebar-layout: Start/Pauze/Stop altijd bovenaan; tabs scrollen; Imp/Fish via Skills-dropdown."),
            new Entry("0.3.245", "2026-08-27",
                    "RuneLite-sidebar: compacte plugin-control (Start/Pauze/Stop + script-dropdown) terwijl Control los hangt."),
            new Entry("0.3.244", "2026-08-27",
                    "Fish: stale 100-tegel pad + ISE; na bank naar dichtstbijzijnde Lure-spot, niet vast 3109,3434."),
            new Entry("0.3.243", "2026-08-27",
                    "WC bank: eerst lopen naar bank (Fishing-parity); stale walk-flag fix in BankHelper."),
            new Entry("0.3.242", "2026-08-27",
                    "Imp/loot invoke: muis eerst op het doel — rode klik-X niet meer linksboven (0,0)."),
            new Entry("0.3.241", "2026-08-23",
                    "Travel altijd rennen; stapvoets lopen alleen als een script dat expliciet zet."),
            new Entry("0.3.240", "2026-08-23",
                    "Lopen: 2–5 = afstand tot gele flag om door te klikken; hop blijft 10–22 tegels."),
            new Entry("0.3.239", "2026-08-23",
                    "Fishing bank: Edgeville stand-tegel + doorlopend walken (geen 11s-pauze / 3× logout)."),
            new Entry("0.3.238", "2026-08-23",
                    "Muis-debug: ours/game = canvas-pixels, geen loopdoel. Example-fidget uit tijdens fishing/SC."),
            new Entry("0.3.237", "2026-08-23",
                    "Banned accounts niet herchecken tot Wis ban-flags. Lopen: bij flag 2–5 tegels doorklikken, geen antiban-stilstand."),
            new Entry("0.3.236", "2026-08-23",
                    "Fishing bank: geen open/dicht-loop — na deposit Close, dan naar spot."),
            new Entry("0.3.235", "2026-08-23",
                    "Control Panel toont script-versies (Fish/WC/Imp) in de header, niet alleen in-game debug."),
            new Entry("0.3.234", "2026-08-23",
                    "Eén walker: fishing en steden-cirkel lopen beide via MovementHelper + TilePath."),
            new Entry("0.3.233", "2026-08-23",
                    "Nabij lopen (fishing) volgt collision-pad zoals steden-cirkel — geen rechte lijn door muren."),
            new Entry("0.3.232", "2026-08-23",
                    "Fishing loopt zoals steden-cirkel: collision-pad, geen rechte lijn door muren."),
            new Entry("0.3.231", "2026-08-23",
                    "Fish-update: launcher staget jars; ↺ Fish in-client zonder Gradle (geen freeze)."),
            new Entry("0.3.230", "2026-08-23",
                    "Herstart bouwt weer installDist; Rebuild-LoneBot.bat — script-reload ≠ launcher v0.3.x."),
            new Entry("0.3.229", "2026-08-23",
                    "Lumb bank-floor: trap overslaan, camera+invoke off-screen, sneller retry — geen stilstand bij trap."),
            new Entry("0.3.228", "2026-08-23",
                    "Fishing: Barbarian bankt in Edgeville (niet Cooking Guild); lopen via pathfinder om manor heen."),
            new Entry("0.3.227", "2026-08-23",
                    "Scripts: staged jars auto bij client-start + launcher-herstel → live clients RELOAD."),
            new Entry("0.3.226", "2026-08-23",
                    "Script-reload: loop eerst pauzeren — geen client-freeze bij WC hot-reload."),
            new Entry("0.3.225", "2026-08-23",
                    "Skill exclusief: ActiveSkill + LoopHost-gate — WC/Fish nooit tegelijk (panel-config race)."),
            new Entry("0.3.224", "2026-08-23",
                    "Fishing bank: eerst vis storten, bait alleen onder min (1× All), Close, dan naar spot."),
            new Entry("0.3.223", "2026-08-23",
                    "WC≠Fish tegelijk; Lumb bank: camera naar booth als die off-screen is."),
            new Entry("0.3.222", "2026-08-23",
                    "Fishing bank: bait in 1× Withdraw-All (geen ×1-loop), daarna sluiten."),
            new Entry("0.3.221", "2026-08-23",
                    "Bank sluiten: echte Close-knop + muis (UI), niet fake 12,2; daarna ESC."),
            new Entry("0.3.220", "2026-08-23",
                    "Lumb bank-floor: booth invoke + loop naar bank-midden (niet stil/Bottom-floor bij zuid-trap)."),
            new Entry("0.3.219", "2026-08-23",
                    "Fishing Draynor: na Bait niet meer wegklikken (bank-straal 8 + geen loop tijdens vis-animatie)."),
            new Entry("0.3.218", "2026-08-23",
                    "Script-reload: fishing.jar niet meer locked — kopie laden + unlock vóór copy."),
            new Entry("0.3.217", "2026-08-23",
                    "Fishing: bank sluiten via Close-knop (CombatBot 12,2) — niet stil blijven met bank open."),
            new Entry("0.3.216", "2026-08-23",
                    "Fishing kookscherm: Space zoals CombatBot (widget 270), niet All opnieuw klikken."),
            new Entry("0.3.215", "2026-08-23",
                    "Fishing na koken: bank via booth-klik + minimap-walk (geen Pathfinder-crash)."),
            new Entry("0.3.214", "2026-08-23",
                    "Lumb bank: alleen zuid-trap (noord-keuze eruit)."),
            new Entry("0.3.213", "2026-08-23",
                    "Fishing cook: vuur via menu-Cook (geen NoClassDefFoundError / TileObjectInteractHelper)."),
            new Entry("0.3.212", "2026-08-23",
                    "Launcher-herstart hangt niet meer op installDist als game-clients open zijn."),
            new Entry("0.3.211", "2026-08-23",
                    "Launcher-herstart laat open game-clients staan (niet alle JVMs doden)."),
            new Entry("0.3.210", "2026-08-23",
                    "Fishing Bait: menu-invoke (niet left-click Small Net)."),
            new Entry("0.3.209", "2026-08-22",
                    "Fishing: loop naar spots (niet center) + ClickOnSight onderweg; Bait klikt geen Small net meer."),
            new Entry("0.3.208", "2026-08-22",
                    "Fishing Draynor: vanaf de bank naar de oever lopen (niet stil in r=14 bij de booth)."),
            new Entry("0.3.207", "2026-08-22",
                    "Fishing bank: Deposit-All per stack sneller (burst); coins niet meer keep."),
            new Entry("0.3.206", "2026-08-22",
                    "Fishing: kookscherm crash (isHidden) gefixt; bank/vuur ClickOnSight; spots eerst lopen dan klikken."),
            new Entry("0.3.205", "2026-08-22",
                    "ClickOnSight: invoke tot 40 tegels, ook off-screen (geen camera/ernaast lopen eerst)."),
            new Entry("0.3.204", "2026-08-22",
                    "Imps: sneller/variabel scatter + deposit; Quantity-All overslaan als die al aan staat."),
            new Entry("0.3.203", "2026-08-22",
                    "ClickOnSight API: klik deposit/sailor zodra op scherm + pad vrij (geen eerst ernaartoe lopen)."),
            new Entry("0.3.201", "2026-08-22",
                    "Fishing: volledige CombatBot-port (Draynor/Barbarian, bait/bank/GE, cook/drop)."),
            new Entry("0.3.200", "2026-08-22",
                    "Bank: scene-klik booth (niet eerst tot 5t lopen); AntiBan skip ≤50t van bestemming."),
            new Entry("0.3.199", "2026-08-22",
                    "Lumb bank: zuid- én noord-trap — kiest snellere (niet altijd noord bij booth)."),
            new Entry("0.3.198", "2026-08-18",
                    "WC yews: sticky chop-target — geen ping-pong meer na eerste Chop down-klik."),
            new Entry("0.3.197", "2026-08-18",
                    "Lumb bank trap: Bottom-floor (niet 1× Climb-down); bot start altijd UIT."),
            new Entry("0.3.196", "2026-08-17",
                    "Alle status-overlays (WC/Imp/Cow/control) hebben een verberg-chip; nieuwe panels krijgen die automatisch."),
            new Entry("0.3.195", "2026-08-17",
                    "Bank-snapshot: geen extra forestry kit kopen als die al in de bank ligt; WC overlay verbergen via chip."),
            new Entry("0.3.194", "2026-08-17",
                    "WC bank: bijl op item-id (geen Bronze dagger-loop); FM last-log failsafe 10s i.p.v. 20s."),
            new Entry("0.3.193", "2026-08-17",
                    "FM failsafe: max 1–2× log op vuur; geen Forester-tend spam op de laatste log."),
            new Entry("0.3.192", "2026-08-17",
                    "WC: boom weg → meteen volgende (niet wachten tot hak-animatie uitfadet)."),
            new Entry("0.3.191", "2026-08-17",
                    "Forestry Entling: juiste prune via invoke (geen left-click Prune-top); chat niet op de verkeerde ent."),
            new Entry("0.3.190", "2026-08-17",
                    "Forestry: alleen groene Rising Root (niet bruine prongs); sapling wacht op juiste pile uit chat."),
            new Entry("0.3.189", "2026-08-17",
                    "FM: geen extra logs op vuur terwijl je al bonfire/Forester-tend doet (CombatBot wait)."),
            new Entry("0.3.188", "2026-08-17",
                    "Inventory-read: tinderbox/logs op item-id + snapshot (geen vals 'geen tinderbox' bij volle inv)."),
            new Entry("0.3.187", "2026-08-17",
                    "FM zonder tinderbox → bank (niet hangen); testknoppen werkten alleen mét tinderbox in inv."),
            new Entry("0.3.186", "2026-08-17",
                    "FM freeze-fix: geen scene-wide getName-scan; loop-thread herstart bij stall (Start/Stop werkt weer)."),
            new Entry("0.3.185", "2026-08-17",
                    "Play = bot AAN (niet 'starten…'); WC-overlay toont AAN/UIT live; example-loop blokkeert WC niet meer."),
            new Entry("0.3.184", "2026-08-16",
                    "WC dual-overlay fix: debug-panel volgt tickende plugin; chat → live hot-reload WC."),
            new Entry("0.3.183", "2026-08-16",
                    "FM live = Test #1 path (tinder→log); geen 'fm tick'-hang meer bij volle inv."),
            new Entry("0.3.182", "2026-08-16",
                    "FM: geen chop→fm hang; WC locatie opslaan gefixt (niet meer → AUTO); UI niet meer dubbel."),
            new Entry("0.3.181", "2026-08-16",
                    "Pathfind: geen incomplete/global-nearest over water; scene-collision eerst + walkable snap."),
            new Entry("0.3.180", "2026-08-16",
                    "WC volle CombatBot-parity: bestTreeInCenter, foreign→bank, skip-tiers, events+kit, idle-edge."),
            new Entry("0.3.179", "2026-08-16",
                    "WC FM = CombatBot: tinder.useOn(log)+anker+3.5s wait; qty/moving/Forester parity."),
            new Entry("0.3.178", "2026-08-16",
                    "FM: geen walkTo/pathfind hang; direct tinder→log; RandomEv eerst + WC in activityAllows."),
            new Entry("0.3.177", "2026-08-16",
                    "WC: boom in scene → meteen Chop down (geen walk-first); client path’t zelf."),
            new Entry("0.3.176", "2026-08-16",
                    "AnimationIds: RuneLite dump (314 names) + JSON/txt; Test-tab anim-dump knop."),
            new Entry("0.3.175", "2026-08-16",
                    "API Animations (WC/FM/bonfire/Forester IDs); overlay toont anim-label."),
            new Entry("0.3.174", "2026-08-16",
                    "WC FM: Forester oid=49927 eerst tenden (geen light-spam); sneller finish→chop; minder useOn-spam."),
            new Entry("0.3.173", "2026-08-16",
                    "WC bonfire: na light → log.useOn(vuur) auto, geen qty-popup-lock."),
            new Entry("0.3.172", "2026-08-16",
                    "WC FM: Test bewees useOn werkt → tickFiremaking roept direct methode #1 aan (geen gate-skip)."),
            new Entry("0.3.171", "2026-08-16",
                    "WC FM: fast-light vóór production/qty-gates; Test-tab 10 light-methodes + Diagnose."),
            new Entry("0.3.170", "2026-08-16",
                    "WC FM: 10 light-methodes (useOn/menu/2-tick/mouse) — roteert bij fail tot vuur brandt."),
            new Entry("0.3.169", "2026-08-16",
                    "WC FM-fix: vals-positief moving (stance) blokkeerde tinderbox; light = tinder.useOn(log) zoals CombatBot."),
            new Entry("0.3.168", "2026-08-16",
                    "WC idle-fix: LoopHost auto-herstart; nooit zonder center; Rimmington oaks in DEFAULT."),
            new Entry("0.3.167", "2026-08-16",
                    "WC firemaking: geen idle chop→fm 8 ticks; tinderbox→log in twee ticks; LoopHost slaapt max 1.2s."),
            new Entry("0.3.166", "2026-08-16",
                    "Storm net.storm.api.widgets: IWidgets/IDialog/ITabs/IFriends/IPrayers/IProduction/IMinigames/IBankWornItems (geen empty stubs)."),
            new Entry("0.3.165", "2026-08-16",
                    "Storm IActor/INPC/IPlayer: attack, interacting, overhead, transform, player-interact (geen false-stub)."),
            new Entry("0.3.164", "2026-08-16",
                    "Storm ItemInfos.lookup: gewicht + combat-bonuses uit item-stats dump (geen lege stubs)."),
            new Entry("0.3.163", "2026-08-16",
                    "Storm Reachable: collision flags, muren/deuren, flood-fill visited tiles, interactable via pad."),
            new Entry("0.3.162", "2026-08-16",
                    "Storm pathfinder-package: ChargeManager, TeleportLoader, TransportLoader (ladders/NPC/dialog/item-use)."),
            new Entry("0.3.161", "2026-08-16",
                    "Storm script-API af: Shop/Trade/Dialog/DepositBox/useOn NPC+ground, Worlds hop, Prayer flush, Bank noted+equip."),
            new Entry("0.3.160", "2026-08-16",
                    "API: Storm InteractManager queue/Automation/WidgetAction; BankSession; WC bank via session."),
            new Entry("0.3.159", "2026-08-16",
                    "API CORE-05/06: BankHelper Draynor+Lumbridge tryOpenFullBank; InteractWalkHelper + WC chop-verify."),
            new Entry("0.3.158", "2026-08-16",
                    "API-blauwdruk: Widget.interact, Bank.open/depositAllExcept/Deposit-invoke (Storm-parity)."),
            new Entry("0.3.157", "2026-08-16",
                    "WC≈CombatBot: log.useOn(vuur), selectief banken, production-keuze, adjacent menu-chop."),
            new Entry("0.3.156", "2026-08-16",
                    "WC: FM useOn (tinder→logs) gefixt; AUTO switch oak→willow bij WC30; boom-pick sneller."),
            new Entry("0.3.136", "2026-08-16",
                    "WC + Imp settings = CombatBot (Skills/Settings: boom, delays, hunt X/Y, GE/teleports, rally, …)."),
            new Entry("0.3.135", "2026-08-16",
                    "GUI = CombatBot tabs: Accounts/Settings/Skills(+sub)/Stats/Centers/Capture/Debug/Test."),
            new Entry("0.3.134", "2026-08-16",
                    "Bot Control volledig (CombatBotPanel): Besturing-balk, LoopWatch, panel-logout, Web GUI, timers."),
            new Entry("0.3.133", "2026-08-16",
                    "Control panel (CombatBotPaint): canvas status/walk/skill; minimize via chip; Overlay-tab toggle."),
            new Entry("0.3.132", "2026-08-16",
                    "WC opnieuw port (bonfire/walk/events; kit-koop behouden); per-script canvas Imp/WC/Cow; full-port rule."),
            new Entry("0.3.131", "2026-08-16",
                    "WC: Console-debug op state/walk/chop/kit/fm/bank; rule lonebot-console-debug."),
            new Entry("0.3.130", "2026-08-16",
                    "WC: shop dicht vóór kit Wear; eerst naar WC-center lopen (geen Chop vanaf bank/forester)."),
            new Entry("0.3.129", "2026-08-16",
                    "Herstart = verse installDist (als desktop-bat); Scripts-tab: herlaad/herstart bovenaan; multi-loader hot-reload Imp/WC/example."),
            new Entry("0.3.128", "2026-08-15",
                    "WC forestry shop: dynamicChildren-scan + Buy-1 menu-invoke op kit (fix CLICK_KIT loop)."),
            new Entry("0.3.127", "2026-08-15",
                    "WC: locatie-keuze; forestry kit detectie (inv/equip id); shop Buy-1 zoals CombatBot."),
            new Entry("0.3.126", "2026-08-15",
                    "Scripts: Woodcutting (Draynor/Port Sarim/yews, bonfire, forestry kit) op Scripts-tab."),
            new Entry("0.3.117", "2026-08-15",
                    "Walk: bij flag + nieuw padpunt korte chain-cooldown (geen 1.6s blokkade)."),
            new Entry("0.3.116", "2026-08-15",
                    "Walk-camera: optie toetsenbord (pijltjes) i.p.v. MMB voor yaw/pitch."),
            new Entry("0.3.115", "2026-08-15",
                    "Walk: 0/400/850 reclick-floor + flag-patience (>10) ook zonder far-canvas."),
            new Entry("0.3.114", "2026-08-15",
                    "Walk: flag-patience weer alleen bij >10 tegels (0/400/850 floor blijft; vereist far canvas)."),
            new Entry("0.3.113", "2026-08-15",
                    "Walk canvas: left-click alleen bij Walk here; anders altijd invoke (geen Chop/Attack/…)."),
            new Entry("0.3.112", "2026-08-15",
                    "Walk: rustiger camera (2.4s/ahead40); korte hops ≤14 zonder flag-wacht; hover fail-closed→invoke."),
            new Entry("0.3.111", "2026-08-15",
                    "Random events: Dismiss via menu-invoke (niet left-click Talk-to); fallback gelijk aan CombatBot."),
            new Entry("0.3.110", "2026-08-15",
                    "Potato no-walk = Get walls kamer-tegels (niet bbox-vierkant); Apply bij scan @3256,3309."),
            new Entry("0.3.109", "2026-08-15",
                    "Potato no-walk = hek-polygoon (niet vierkant); Capture-tab + volledige Get walls report."),
            new Entry("0.3.108", "2026-08-15",
                    "Walk-pitch default 3064 (niet 306); Get walls / Get walls (NPC) + muren-overlay."),
            new Entry("0.3.107", "2026-08-15",
                    "Walk-pitch default 306; Lumbridge potato field no-walk (strak 3244–3262,3301–3317); overlay oranje."),
            new Entry("0.3.106", "2026-08-15",
                    "Canvas-walk: echte Walk-here left-click (tiles zichtbaar); invoke alleen bij boom/NPC. Camera: 1 MMB i.p.v. 2."),
            new Entry("0.3.105", "2026-08-15",
                    "Walk-cam: zoom/pitch weer bij lopen; minder yaw-spam (throttle 1.8s, yaw alleen als ahead<52%); default zoom verder uit."),
            new Entry("0.3.104", "2026-08-15",
                    "Hiscore-ban: alleen echte 404=banned; netwerkfout wijzigt flag niet; Force hercheckt banned; Wis ban-flags."),
            new Entry("0.3.103", "2026-08-15",
                    "Launcher: 📁 Logs + ↻ Imp (apart script-imp-killer, hot-reload zonder client-herstart)."),
            new Entry("0.3.102", "2026-08-15",
                    "Canvas: korte hops zonder 1.2s-floor; random events (Dismiss/Genie/lamp) vanuit CombatBot."),
            new Entry("0.3.101", "2026-08-15",
                    "Far/canvas: wacht tot dicht bij flag vóór herklik; Walk-here invoke (geen boom/NPC); geen twin-spam."),
            new Entry("0.3.100", "2026-08-15",
                    "FOLLOW=bestemming vooruit op scherm (niet alleen yaw%); MMB + setYaw-fallback voor steden-cirkel."),
            new Entry("0.3.99", "2026-08-15",
                    "FOLLOW-fix: skip pas bij face≥75% + bestemming vooruit; 23% skiptte te vroeg (camera bleef scheef)."),
            new Entry("0.3.98", "2026-08-15",
                    "Yaw mode/offset/pitch/zoom: camera draait meteen bij wijzigen (live preview)."),
            new Entry("0.3.97", "2026-08-15",
                    "Walk-cam: 1 gebogen MMB (H+V, offscreen); geen pitch-terugtrek bij lopen; geen setYaw-snap."),
            new Entry("0.3.96", "2026-08-15",
                    "Walk-cam: 1 vloeiende MMB (snelheid×afstand, random start buiten UI); skip bij ≥30% zicht; pitch~350; overlay angles."),
            new Entry("0.3.95", "2026-08-14",
                    "Walk-camera: menselijke MMB-drag; pitch/zoom fijne sliders (stap 1); zoom 0–100%."),
            new Entry("0.3.94", "2026-08-14",
                    "Walk-camera sliders: FOLLOW/CONTRA/offset, pitch, zoom + Walk+camera test + rapport-kopie."),
            new Entry("0.3.93", "2026-08-14",
                    "Walk-camera test: popup + before/after yaw/pitch/scale; duidelijke fout als niet ingelogd."),
            new Entry("0.3.92", "2026-08-14",
                    "Walk-camera: yaw naar looptegels, volledig uitzoomen, pitch ~300 (niet horizon-laag)."),
            new Entry("0.3.91", "2026-08-13",
                    "DWM-previews alleen op Clients-tab — niet meer hangen op Accounts/News."),
            new Entry("0.3.90", "2026-08-13",
                    "Clients-tab: live DWM-previews van alle clients + schaal-slider (geen samenvoegen)."),
            new Entry("0.3.89", "2026-08-12",
                    "Clients-samenvoegen/DWM/embed verwijderd — terug naar simpele Clients-lijst + losse vensters."),
            new Entry("0.3.88", "2026-08-12",
                    "Samenvoegen = minimaliseren (werkt); 1 client = alleen grote tab-preview; auto-merge."),
            new Entry("0.3.87", "2026-08-12",
                    "DWM op top-level Clients-frame (fix E_INVALIDARG); Focus/Minimaliseer i.p.v. embed."),
            new Entry("0.3.86", "2026-08-12",
                    "DWM-fix: geen off-screen park; struct-padding; stabiele Canvas-HWND + debug-log."),
            new Entry("0.3.85", "2026-08-12",
                    "DWM vindt clients via PID (titel was ‘RuneLite’); stale HWND-IPC genegeerd."),
            new Entry("0.3.84", "2026-08-12",
                    "Echte DWM live mini+tab (geen screenshots): clients top-level off-screen geparkeerd."),
            new Entry("0.3.83", "2026-08-12",
                    "Mini’s: DWM live-thumbnail (taakbalk-stijl); screenshot alleen als fallback."),
            new Entry("0.3.82", "2026-08-12",
                    "Mini’s per client via eigen preview.jpg (geen gedeelde tab); scherper 720p/JPEG92."),
            new Entry("0.3.81", "2026-08-12",
                    "Imp-checkbox afvinken blijft uit; mini’s weer per client (niet alleen actieve tab)."),
            new Entry("0.3.80", "2026-08-12",
                    "Mini: alleen actieve tab + schaal-slider 100–300% (opgeslagen)."),
            new Entry("0.3.79", "2026-08-12",
                    "Mini preview: PrintWindow geschaald (hele client) i.p.v. DWM-hoek; snellere preview.jpg."),
            new Entry("0.3.78", "2026-08-12",
                    "Mini=DWM geschaald (hele client); tabs=volle embed; Samenvoegen terug in tab."),
            new Entry("0.3.77", "2026-08-12",
                    "Echte mini-previews (geen flikker), focus-steal harder uit, Samenvoegen hersteld."),
            new Entry("0.3.76", "2026-08-12",
                    "Live mosaic Overview terug; geen focus-steal bij client-start/embed."),
            new Entry("0.3.75", "2026-08-12",
                    "Clients: altijd embed in tabs; stale sessie-tabs weg; Samenvoegen herstelt embed."),
            new Entry("0.3.74", "2026-08-12",
                    "Clients apart van launcher: multi-tab venster + loskoppelen tot eigen client-venster."),
            new Entry("0.3.73", "2026-08-12",
                    "HWND mosaic fix: park-before-reparent + client window.hwnd IPC (vensters niet meer kwijt)."),
            new Entry("0.3.72", "2026-08-12",
                    "Clients: live HWND mosaic (2x2/3x3/4x4), focus-tab, detach — geen screenshot-lag."),
            new Entry("0.3.71", "2026-08-12",
                    "Per-account Imp/Cow skills + launcher Clients-tab (minis, detach, dubbelklik)."),
            new Entry("0.3.70", "2026-08-11",
                    "Walk: flag-proximity reclick, 2 snelle kliks, far-cam draait mee met looprichting."),
            new Entry("0.3.69", "2026-08-11",
                    "Walk/Travel: stap min/max, reclick, delays, far-canvas (lage camera + ver klikken)."),
            new Entry("0.3.68", "2026-08-11",
                    "DevTools: widget hover, inv/NPC/object/ground IDs, middenklik + dump → Console."),
            new Entry("0.3.67", "2026-08-11",
                    "Muis-debug (kruisje) los van status overlay — aparte toggle."),
            new Entry("0.3.66", "2026-08-11",
                    "Autocast: wait Combat-tab + picker-al-open skip + muis-fallback Choose spell."),
            new Entry("0.3.65", "2026-08-11",
                    "Magic spells: vaste InterfaceID widgets (Wind Strike=218,11) i.p.v. name-scan."),
            new Entry("0.3.64", "2026-08-11",
                    "Autocast: dyn-child invoke met action+index (Fire Strike var276=4)."),
            new Entry("0.3.63", "2026-08-11",
                    "Test-tab: autocast dropdown + testknop (meerdere select-methodes + dump)."),
            new Entry("0.3.62", "2026-08-11",
                    "Autocast: Combat Options + setAutoCast(spell,false) + varbit-check (CombatBot)."),
            new Entry("0.3.61", "2026-08-11",
                    "Attack: invoke-first + muis-verify (geen walk naar oude NPC-tegel)."),
            new Entry("0.3.60", "2026-08-11",
                    "Mage: autocast 1× daarna alleen Attack (geen magic-tab per kill)."),
            new Entry("0.3.59", "2026-08-11",
                    "Walk doorsturen+DBL fix; boat camera→invoke; Fire Strike autocast zoals CombatBot."),
            new Entry("0.3.58", "2026-08-11",
                    "Snellere walk+DBL; gear dump verkeerde staff; console-log; Imp debug zichtbaar."),
            new Entry("0.3.57", "2026-08-11",
                    "Imp debug weg bij bank; runes Withdraw-All invoke; Withdraw-X fix."),
            new Entry("0.3.56", "2026-08-11",
                    "Dubbele News-knop weg; account-knoppen compacter in rijen."),
            new Entry("0.3.55", "2026-08-11",
                    "FlatDarkLaf + donkere tabelkop/tabs (leesbaar contrast)."),
            new Entry("0.3.54", "2026-08-11",
                    "Herstart via client.bat (fix ClassNotFound); stabieler op Windows."),
            new Entry("0.3.53", "2026-08-11",
                    "Launcher dark theme (geen witte achtergrond); Update herstart automatisch."),
            new Entry("0.3.52", "2026-08-11",
                    "Launcher: Herstart / Update / News-knoppen rechtsboven + changelog-tab."),
            new Entry("0.3.51", "2026-08-11",
                    "News-tab op launcher; update-instellingen in ~/.lonebot/update.properties."),
            new Entry("0.3.50", "2026-08-11",
                    "Herstart laadt SDK/client-build; behoudt launcher- of client-rol."),
            new Entry("0.3.49", "2026-08-11",
                    "Bank: withdraw via menu-invoke; gear nooit Withdraw-All."),
            new Entry("0.2.23", "2026-08-11",
                    "Imp: gear-check, style armour, action logs, slim overlay.")
    );

    private LoneBotChangelog() {
    }

    public static List<Entry> entries() {
        return Collections.unmodifiableList(ENTRIES);
    }

    public static String asHtml() {
        StringBuilder sb = new StringBuilder("<html><body style='color:#d8dce8;font-family:sans-serif;'>");
        sb.append("<div style='margin-bottom:8px;color:#f0a050;'><b>Wat is er nieuw</b></div>");
        for (Entry e : ENTRIES) {
            sb.append("<div style='margin:0 0 10px 0;'>")
                    .append("<b style='color:#8ec8ff;'>v").append(escape(e.version)).append("</b>")
                    .append(" <span style='color:#9aa3b5;'>").append(escape(e.date)).append("</span><br>")
                    .append(escape(e.summary))
                    .append("</div>");
        }
        sb.append(LoneBotScriptChangelog.asHtml());
        sb.append("</body></html>");
        return sb.toString();
    }

    private static String escape(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
